### ISSUE TITLE
FPP 5.4.1 Freezes Daily - Requires FPPD Restart

### ISSUE THREAD

**Issue by jholmes09** [FalconChristmas/fpp#1192] opened 2021-12-09 05:23 UTC
**FPP Version and Hardware**: 
- FPP 5.4.1 (I have also tried 5.3 and 5.3.1)
- Raspberry Pi 3B+
- There is no router or RTC on network
- 30 to 40 pixel controllers (it varies, I'm having this issue in multiple places)

**Describe the bug and Steps to reproduce**: 
Please see linked ZIP with JSON and associated FSEQs and Media Files.
I have tried attaching this but I keep getting an error:
https://iwgproductions.sharepoint.com/:u:/s/GeneralAdministration/EXLBdRaogLdLluC6aEB7ka8BIaNa8mjAUzTtVHnl6umYfQ?e=Ch9QUd

Scheduled 'idle' playlist plays on loop whenever Pi is powered (24/7 schedule).

GPIO trigger activates multiple Command Preset Slots, some of which activate other GPIOs and manually override to a "show" playlist. The sequence in the show playlist also contains a Command Preset channel (channel 1) which turns on/off a GPIO every 0.5 seconds. 

Sometimes, FPPD will stall. Web interface is accessible but shows no information (like idle, playing, or the clock). GPIOs are unresponsive and pixels turn off. Must click Restart FPPD to get anything working again.

**Comment by darylc** [comment] 2021-12-09 06:35
Please turn on debugging then provide the log after another crash

**Comment by jholmes09** [comment] 2021-12-09 17:34
@darylc Do you want all options set to Debug or just a select few?

**Comment by jholmes09** [comment] 2021-12-11 00:41
Hi All,

We were able to catch the issue in the act twice, once with FPP 5.3 and once with FPP 5.4.1.
Logs are all set to Debug. I have included the sequence files, mp3, FPP settings, and zipped logs.

FPP 5.3 Folder:
https://iwgproductions.sharepoint.com/:f:/s/GeneralAdministration/Erp1TnOuI-tLqH-9WZahcGoB7B406U0t3lrMLU5VeB7dLQ?e=XnCpa6

FPP 5.4.1 Folder:
https://iwgproductions.sharepoint.com/:f:/s/GeneralAdministration/EpLg5kQwn-xKjMBmbLamwU0BdlcyMII2UYyufXKhJFakhA?e=X77dtw

Additionally, please see screen-shots of what FPP UI looks like when I go to the web browser.
The only thing I have to do to 'unstuck' FPP is press "Restart FPPD".

![Zone 3 Web UI Stall](https://user-images.githubusercontent.com/18503894/145657264-7200495d-08c1-4a9b-b6ec-180d6cf6a603.png)

![Zone 4 Web UI Stall](https://user-images.githubusercontent.com/18503894/145657268-be56b03f-cf53-4a1b-bc27-4c6cb1d61adb.png)

**Comment by patdelaney** [comment] 2021-12-11 00:53
do you happen to know what time if froze up?

**Comment by patdelaney** [comment] 2021-12-11 01:00
I've been chatting with Jeffrey about this over the last few days. I'm not sure its documented in the bug, each one of these Pi's is running stand alone and they are triggered by GPIO. The GPIO are wired to the Pi, no GPIO hat.  For the developers that are looking at the logs, my gut thinks it related to the GPIOs and what they are triggering. I think he ran a test during the day with just a playlist looping and no GPIO triggers and there were no issues.

**Comment by jholmes09** [comment] 2021-12-11 01:33
Hi all;

1) The units are not attached to RTC or internet so the timestamp will be all screwy. The issues should be present near the end of the logs as, when we learned of the freeze, I immediately had someone connect to the network, restart FPPD and download the log files. 

2) Yes, I ran a 4 hour test in which I selected my “show” playlist and fold FPP to play “repeated.” This was done from the web interface with a cellular router connected during the entire test. No issue occurred. 

3) A sensor trips a relay which closes a GPIO circuit, which tells FPP to start the show. I also have GPIO circuits that I flip on / off from FPP to turn on/off indicator lights for staff. One GPIO is triggered by a command channel in the show sequence itself.

**Comment by jholmes09** [comment] 2021-12-14 05:34
Update:

In attempt to mitigate the issue until we find the cause, I added a script that restarts FPPD after every triggered show. 

Since doing this, we have not had a problem in two nights across nine different shows. 

I’m not sure what this tells you but I hope it helps shed some light onto what may be the cause.

**Comment by patdelaney** [comment] 2022-02-16 00:03
@jholmes09 I been able to replicate the what I believe is the same issue that you are reporting. I was able to reproduce it by running a playlist with a single 5min sequence. I assigned a GPIO to start a playlist. I then added a separate relay on a timer that would simulate the button push about every 10 seconds. The expected behavior is when the button is pushed, the current playlist stops and then the playlist assigned to the button is played.
![image](https://user-images.githubusercontent.com/8147459/154169652-4ce03122-7fad-4a64-a121-698d9d513e8e.png)
I ran this setup over night and the next day I checked in on it and the FPP UI was in a what I would call a zombie state, the screen is there, but all the data that is populated on the UI by FPP is missing.
![image](https://user-images.githubusercontent.com/8147459/154169795-f0ae0d95-2129-4347-bf34-2a8ee3b341d8.png)
I then opened up a putty/ssh session to the pi and ran the top command and saw that fppd was using 270% of the CPU, that's not good.
![image](https://user-images.githubusercontent.com/8147459/154169947-7c2666b1-e4a5-46c2-a461-9775981b33c4.png)
I exited out the the top command and ran the following:
sudo strace -p 1331   
(1331 is the PID or process ID from the top command, that is running fppd)
it appears that fppd ran out of file handles
_openat(AT_FDCWD, "/home/fpp/media/logs/fppd.log", O_WRONLY|O_CREAT|O_APPEND|O_LARGEFILE, 0666) = -1 EMFILE (Too many open files)_

I was able to replicate the issue the next day as well. Now we have a repeatable set of steps to cause the issue and then once the developers fix it, I then have the steps to test the fix.

**Comment by LightsOnHudson** [comment] 2022-02-16 19:35
@patdelaney Great work - because we had this happen, but not on triggers. We did have Remote commands going to remotes. to turn projectors on and off. A reboot before the show seemed to help it. so closing those open file handles as a bandaid?

**Comment by msimmons78** [comment] 2022-02-16 22:08
Why are there so many open handles in these situations?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cpinkham** [comment] 2022-02-19 04:32
The issue Pat was seeing in testing has been fixed in the master and v5.5 branches.  The issue had to do with starting a .fseq as a playlist.  When you tell FPP to play a .fseq as if it were a playlist, the code auto-generates a playlist for the .fseq file.  In doing so, it opens the fseq file to check if there is an accompanying media file to play.  This is where the issue occurred.  The instance of the fseq that was opened was never closed, so every time you started a .fseq as a playlist, FPP would leak a file and eventually could run out of file handles.  This likely also caused a small memory leak.

I will leave the ticket open for now until we confirm that fixed the problem originally reported.  I am 99% sure it fixes the issue that Pat was able to reproduce in testing based on how he was running the test.

**Comment by cpinkham** [comment] 2022-02-25 09:08
Closing ticket since Pat's test has been running for days without any issues.  Reopen if anyone can still reproduce the issue.

**Closed by cpinkham** 2022-02-25 09:08 UTC
Labels: bug
