### ISSUE TITLE
Missing Codecs on v5

### ISSUE THREAD

**Issue by MrPaulAR** [FalconChristmas/fpp#1079] opened 2021-08-28 21:18 UTC
**FPP Version and Hardware**: 
Pi 4 v 5.1.1

**Describe the bug and Steps to reproduce**: 
We've seen this twice now in the xLights zoom room so today I tried to duplicate this and I was able to duplicate the issue and provide a fix for the end user.  This example uses the 2020 XLATW Into the Unknown video that works fine in FPP 4.6 but is not recognized in 5.1.1.

![image](https://user-images.githubusercontent.com/3765696/131231195-0742fdf5-b70f-418e-a6e6-824f67411c13.png)

To fix the issue I just passed it through ffmpeg and did a direct stream copy with no re-encode (ffmpeg -i infile -c copy new.mp4).  I'll attach both mp4 files to this.

Looking at the mp4 files with mediainfo I do not see any significant issues with the codec but I may be overlooking something.

**Expected behavior**: 
Video output is displayed on the output device and the duration shows in the file manager.

**Additional context**: 
I used my own local copy of this file without getting it from the other user. 

**Note**
I tried to upload these mp4 files to the ticket but I need to shrink them which defeats the purpose.  The specific video with the issue is panic-at-the-disco-into-the-unknown-from-frozen-2.mp4

**Comment by MrPaulAR** [comment] 2021-08-28 21:37
Files in question are here https://mega.nz/folder/4ohGXI6L#xjHAioaehCysyKSsRzjo3A

**Comment by ghormann** [comment] 2021-09-11 01:27
I attempted upgrading to the latest stable version of GetId3  (1.9.16 -> 1.9.20).   Same problem exists.   There is a divide by zero error with the file that doesn't work.   A key difference I see (other than codec) is that the "new" file has a constant bit rate.   I'm not  sure if that matters much though... 

I'd be curious to know if the problem is just with displaying the size, or if it really doesn't play .   (I didn't have an HMI device to test with).

**Comment by cpinkham** [comment] 2021-11-20 01:00
We probably should switch the metadata collection to use ffprobe which is used when you use the metadata API call.  ffprobe does work correctly for both of these files.

api/controllers/media.php calls GetMetaDataFromFFprobe() which is in common/metadata.php and calls out to ffprobe to get the metadata about a video file in JSON format.  This is a little slower than GetId3, but if we are caching the result it shouldn't impact loading too often.

**Comment by darylc** [comment] 2023-01-24 10:25
@MrPaulAR Is still still a problem in v6.3?

**Comment by MrPaulAR** [comment] 2023-01-24 14:12
Not sure if it impacts every video but this specifc one is still an issue.

5.5
![image](https://user-images.githubusercontent.com/3765696/214316356-6e43be98-4fd5-4f1e-aea6-e0a80550b62c.png)

6.3
![image](https://user-images.githubusercontent.com/3765696/214316445-dc0d0f48-ea12-4482-b9d5-b6c7c92fa7fd.png)

Note that the duration is still unknown (guessing some error handling sets it to 0 on the front end).  

I don't have hdmi output on these (P5s) so I cannot test if it is cosmetic or not.  I expect that if vlc is doing the output it'll play just fine though.

**Comment by darylc** [comment] 2023-01-26 10:25
@MrPaulAR Can you please provide a link to this file?  https://mega.nz/folder/4ohGXI6L#xjHAioaehCysyKSsRzjo3A no longer works.

**Comment by MrPaulAR** [comment] 2023-01-26 15:19
I've uploaded the original file again to https://mega.nz/file/1hxFzIxL#xco4MDmrhD73Ka0tEDsJWH7H1SSFn8vWuNBxbo3Zlck

If that doesn't work you probably already have it as it's from the 2020 XLATW Into the Unknown (panic-at-the-disco-into-the-unknown-from-frozen-2.mp4).

**Comment by darylc** [comment] 2023-01-27 04:09
Thanks the file, should be fixed now.

**Closed by darylc** 2023-01-27 04:09 UTC
