### ISSUE TITLE
Panels on Octoscroller fail to work on FPP v4.1

### ISSUE THREAD

**Issue by syracuse-lights** [FalconChristmas/fpp#783] opened 2020-08-23 02:33 UTC
I have a Kulp BB Octscroller running v4.0.1 with six P10 panels configured at 2x3..

Works great in xlights and locally on the BB, test also works.

> Upgrade to v4.1

Panels no longer work in xlights or locally. Run the local test on FPP and I get 1 pixel that lights up red and flashes.

> Downgrade to v4.0.1

Panels work in xlights and locally on the BB through FPP, test on FPP displays all white as expected.

![image](https://user-images.githubusercontent.com/69699152/90969441-fb9ff880-e4b5-11ea-9edc-39f1dd56a20b.png)

**Comment by ghormann** [comment] 2020-10-06 23:43
@syracuse-lights  Is this still an issue in 4.2?   I'm unable to reproduce on 4.2, in Bridge mode, using BBB with diyledexpress Octoscroller.   Tested with both e1.31 and DDP.

**Comment by syracuse-lights** [comment] 2020-10-07 00:09
No, 4.2 is working as expected

Matthew

**Comment by ghormann** [comment] 2020-10-07 00:10
Thanks. closing.

**Closed by ghormann** 2020-10-07 00:10 UTC
Labels: Need Info
