### ISSUE TITLE
Display Testing - add port test

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1417] opened 2022-11-25 14:49 UTC
Now that we are able to run large numbers of pixel string ports it would be helpful if the display testing UI was expanded to include a port test capability. (ignoring model definitions and just test pixels connected to port)

This would be useful to be able to select one port at a time and see which props are connected to it - will helping identifying where things have been installed differently to the uploaded config.

If the test sequence was able to chase RGB and work its way through each connected pixel in order (e.g. 1 , 1+2, 1+2+3 etc..) that would also allow the user to see which props follow which when they are daisy chained together.  Would be good to be able to control the speed at which each successive pixel is added to the testing string to cater for those with high density props as well as those with only small numbers of pixels connected

**Comment by bcarriveau** [comment] 2022-11-27 16:23
People should have to do SOME troubleshooting in real life in this hobby 🙈 or at the very least be punished for being sloppy while setting up 😬🙈

**Comment by darylc** [comment] 2023-01-01 11:52
duplicate of #839

**Closed by darylc** 2023-01-01 11:52 UTC
Labels: enhancement
