### ISSUE TITLE
healthCheck.php not displaying correctly

### ISSUE THREAD

**Issue by OnlineDynamic** [FalconChristmas/fpp#1522] opened 2023-06-23 23:48 UTC
**FPP Version and Hardware**: 
[v7.x-master-118-ga91d7a52 (master branch)]
rpi zero w

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to healthceck.php
2. Results not fully displaying

**Expected behavior**: 
window to load correctly

**Additional context**: 
the healthcheck script seems to be running ok and can't see any issue in php output
is this a timeout issue as on a rpi zero w ??
or is this bootstrap upgarde related?

**Additional Attachments**
screenshot
![healthCapture](https://github.com/FalconChristmas/fpp/assets/68251154/55acd8da-8a35-404d-8af7-5ec9c65f6bb9)

**Comment by ghormann** [comment] 2023-06-24 00:12
I think this is the problem.     The output of `healthCheckHelper.php?output=php` is failing eval. 
![image](https://github.com/FalconChristmas/fpp/assets/24968726/9abc802d-1bb7-4edf-8264-7638cda6d51a)

**Comment by ghormann** [comment] 2023-06-24 00:43
I'm not able to reproduce the problem with "Root File system" staying in `running` on PI3 or BBB.   I think this *may* be a timeout issue, but don't have the hardware to check. 

I did find a bug where the Recheck Health button (as well as other buttons) were staying disabled.   I pushed a fix to master for that issue.

**Comment by OnlineDynamic** [comment] 2023-06-24 10:25
Checked with a different broswer and works fine on:

Microsoft Edge
Version 114.0.1823.51 (Official build) (64-bit)

so this is related to firefox:
114.0.2 (64-bit)
![healthCapture](https://github.com/FalconChristmas/fpp/assets/68251154/a8766870-f227-4d3a-921a-9579da37d30e)

**Comment by bobreese** [comment] 2023-06-24 12:01
Working fine with Google Chrome

**Comment by ghormann** [comment] 2023-06-24 13:18
If you do a forced refresh (Cmd + Shift + R) to reload the javascript and css on firefox does it fix it?   I'm not able to reproduce on Firefox. 
![firefox_jRbfV5ba1O](https://github.com/FalconChristmas/fpp/assets/24968726/bbae1962-d8ac-474f-b2f1-b21482f9cd3d)

**Closed** 2023-06-24 17:35 UTC

**Comment by OnlineDynamic** [comment] 2024-02-05 14:46
Added fix for firefox on windows 11 in PR in commit: [122f86e](https://github.com/FalconChristmas/fpp/pull/1765/commits/122f86e843ad718eb90e7224e639364e3ed5b8fd)

**Comment by OnlineDynamic** [comment] 2024-04-03 21:17
Still an issue and my last attempt to fix sorted firefox but was then problematic for others on different setups...
![image](https://github.com/FalconChristmas/fpp/assets/68251154/33c8d13b-f11c-4519-8919-5cbc1ba58d0d)

I have now narrawed down the issue to the StreamURL function...  I have replaced that with a simple ajax call instead for the loading of the healthchecker screen.  Raised PR xx with the patch to fix - can someone test it still works on their setups... seems good in FireFox and Edge for me
