### ISSUE TITLE
No reboot from Web Interface

### ISSUE THREAD

**Issue by dugEfresh25** [FalconChristmas/fpp#1225] opened 2022-01-05 18:45 UTC
When I click the reboot button from the web interface, the Pi does start a reboot process, but does not come back online. The status lights are on, but will not be able to reconnect to FPP IP address until I electrically reboot the device. This has happened on V4 all the way through V5.4.1 firmware, Pi 4. 

If FPP needs to reboot for a change, the change will take, but reboot issue still occurs.

This is on a Rasberry Pi4 with 5.4.1, but as noted happened with latest v4 firmware as well. 

I have tried on 2 different Pi's, 2 different SD cards, completely re imaged SD card with no changes, and reboot error still occurs. 

Please see attached logs. [Thanks](url)

**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

[FPP_Logs_20220105.1839.zip](https://github.com/FalconChristmas/fpp/files/7817080/FPP_Logs_20220105.1839.zip)

**Comment by patdelaney** [comment] 2022-02-06 02:20
I can't reproduce this. What web browser and version of Web browser? Is the browser PC or Mac based?
Are you on ethernet cable or wireless?

Thanks

**Comment by patdelaney** [comment] 2022-02-06 02:25
Are you talking about this reboot button?
![image](https://user-images.githubusercontent.com/8147459/152665552-1faf691f-3a53-4f77-9419-9e35b1a4c15b.png)

**Comment by Poporacer** [comment] 2022-02-06 02:35
I cannot duplicate it either.

**Comment by dugEfresh25** [comment] 2022-02-06 02:56
This happens on chrome IE and safari. Using a PC windows 7 and also an iPhone.

Wired connection.

I do believe it happens on wireless as well.

**Comment by dugEfresh25** [comment] 2022-02-06 02:56
Yes that button, but also happens in terminal

**Comment by ghormann** [comment] 2022-02-06 13:49
Does the device actually restart?  (e.g. if you have a monitor plugged in do you see the Raspberry Pi boot screen?) 

A number of us have tried and have no clue how to reproduce this.   There is nothing obvious in the logs.

**Comment by patdelaney** [comment] 2022-02-15 22:38
We have not been able to reproduce the issue the way you described, but we did find an issue when you are doing a version upgrade. The reboot button on the top dialog was not passing the reboot command down to the FPP. That fix is in Master Branch for Fpp6.x  https://files.slack.com/files-pri/T0SRF4F19-F031VKB9DF0/image.png

**Comment by patdelaney** [comment] 2022-02-15 22:40
@dugEfresh25  Can you reproduce this at will?

**Comment by dugEfresh25** [comment] 2022-02-15 22:51
Yes it happens every time.

**Comment by Poporacer** [comment] 2022-02-15 23:35
@dugEfresh25 
Could you do a video screen capture so we can see how it is happening?

**Comment by Poporacer** [comment] 2022-02-19 05:05
Whatever it is that you are seeing. Since you are probably using the web UI, then that, unless you are using something else to make your observations.

**Comment by dugEfresh25** [comment] 2022-02-21 17:50
I am using the web UI. Nothing really happens. I click reboot, the UI disconnects, then just doesn't re connect. I do a constant ping to the PI and I can see it fall offline. It will not start pinging again no matter how long I wait. It is a static IP. Once I electrically reboot the PI, the same constant ping will reply to the PI and I can reconnect to the web UI.
    On Friday, February 18, 2022, 09:05:42 PM PST, Poporacer ***@***.***> wrote:  
 
 


Whatever it is that you are seeing. Since you are probably using the web UI, then that, unless you are using something else to make your observations.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by darylc** [comment] 2023-01-07 05:25
given we can't replicate this and no others users have report this, I'm not sure what we can do.

**Closed by darylc** 2023-01-07 05:25 UTC
