### ISSUE TITLE
Create playlist from selected entries in the file manager

### ISSUE THREAD

**Issue by blargh2947** [FalconChristmas/fpp#1725] opened 2023-12-19 14:53 UTC
**Is your feature request related to a problem? Please describe.**
As a user, I would like to create a playlist with multiple entries quickly.  

**Describe the solution you'd like**
From the file manager, select multiple sequences in the UI
Add a button for "Add all to Playlist" and "Add all to new playlist"
The function then adds the sequences to the end of a selected current playlist, or creates a new playlist and adds the entries.

**Describe alternatives you've considered**
N/A

**Additional context**
Some users may create multiple playlists for different days or needs.  Also if I want to quickly add a few sequences to an existing playlist this work flow would be faster.

**Comment by cpinkham** [comment] 2023-12-21 20:40
Duplicate of #1702.

**Closed by cpinkham** 2023-12-21 20:40 UTC
Labels: enhancement
