### ISSUE TITLE
FPP Scheduler/Playlist Issue

### ISSUE THREAD

**Issue by McCoyCOREUSA** [FalconChristmas/fpp#1687] opened 2023-12-02 17:46 UTC
FPP v7.3.5 (7.3 branch)
Pi 4
xLights 2023.21
Pixel-2-Servos-12 (board)
Falcon F16V3 (2.59)

This has been an issue for a long time. No idea what version is started with, since this was originally thought to be an xLights issue last year. After working through xLights stuff for the past year or so, further investigation leads me to believe it's a FPP issue. 

OVERVIEW
I'm using servo effect for servos that control an animatronic Santa that I built. Last year, I built only the left arm to test and figure it out. I programmed movements for the left arm only. I had problems with the left arm launching upward. I removed the sequencing that controlled the arm, rendered, uploaded. The left arm continued to trigger with no data. This appeared to be cached or hidden data stuck in the sequence for the servos -- so I submitted this issue last year to xLights. They dug through the files and found nothing.

This year, I rebuilt the left arm and also built the right arm.

At the beginning of my show, I have a sequence that is only about 15 second long and is Santa saying "Welcome to the McCoy Family Christmas Lights Show!" This sequence was made last year and programmed with the left arm only, because that's the only arm I built. I started using this same sequence this year and checked that there is NO sequencing for the Santa servos other than the mouth servo. Rendered and uploaded, as usual. 

This "welcome" sequence is in my FPP playlist in Lead In. This year, it continues to launch the left arm upward and it stays. I've watched it every night when the show scheduler begins, and it does the exact same thing.

Here is what I found so far: 

- The arm launches upward on the short welcome sequence in Lead In.
- This happens ONLY when the scheduler launches the Playlist. When I start the playlist manually, it doesn't do it. 
- It's definitely the welcome sequence that triggers the arm, even with no data/sequencing in it. I tried removing all servo effects from the sequence.
- It's only the left arm. Santa has 10 servos (two arms, neck, mouth) and only the left arm is triggering in the welcome sequence. However, that was the only arm programmed last year in this sequence when it was first created, but that sequencing data was removed last year because of this issue.

In my effort to investigate further, I decided to create a new 'welcome' sequence from scratch. I figured there must still be hidden data in it from last year that is triggering the arm. I used the same audio file, but the sequence is brand new. I didn't any arm movements to the servos. I gave the sequence a new name, rendered, uploaded to FPP. I then removed the old welcome sequence from the playlist and added the newly created sequence. 

After replacing with the newly created sequence, the show began last night as the arm still activated as usual!

I'm at a total loss. This issue seems to be something with FPP triggering old data somehow? And it's only when the playlist is started by the scheduler. I've spent two years trying to figure this out and multiple times help from the Zoom Room, and we are all at a loss.

FILES: https://mccoycloud.com/index.php/s/BcJ5o9TJFBiSf69

**Comment by cpinkham** [comment] 2023-12-04 00:37
Other than blanking data at startup, FPP is only going to send what you tell it to send, and it can't get old data unless it is in a fseq/eseq file.  Do you have any Command Presets setup that could be running an effect?  You could crank up the debug level and restart fppd then look at the log file to see if anything stands out such as if any effect sequences were run.

**Comment by McCoyCOREUSA** [comment] 2023-12-04 01:54
No effects. They guys in the Zoom Room thought a "turn off all lights" command just before the sequence that was triggering the servos might help. The start of last night and tonight have not had the issue yet.

**Comment by cpinkham** [comment] 2023-12-05 22:31
FPP should send blanking data when it starts or stops a playlist and also when fppd starts.  If you have to send a Turn Off All Lights before your sequence starts playing then it points to other issues.  The channel data array should be filled with zeros unless there is something else other than a sequence setting the values.  This could be something like a Pixel Overlay Model or a running effect sequence.

Are you sure the issue isn't in your "SEQ Santa Servo Reset.fseq" sequence instead?  If it works correctly when you manually play "Show Welcome MOUTH ONLY.fseq" but not when you run it from the playlist, then I would look at the Reset sequence instead.

**Comment by McCoyCOREUSA** [comment] 2023-12-05 23:47
The 'all lights off' was a suggestion from the Zoom Room. Tonight, it made no difference. Santa's left arm went up on the welcome sequence, as it does 90% of the time (but only when the playlist is started by FPP). 

The Santa Servo Reset sequence was added to place Santa back into his rest position. I haven't had issues with that. But the welcome is triggering him. There is no data to the left servo arm in that sequence, but it acts as if there is. That's even a brand new sequence added to make sure it was new/fresh.

Today, I also moved to another port on the Falcon F16V3. Yesterday, I isolated the servo board power that runs the board from the pixel port, so it's on its own power supply separate from the controller. I also replaced the Pixels-2-Servos12 board today. Still getting same results. Manual testing from xLights per servo worked fine.

I'm down to the sequence having some hidden data in it? Everything has been replaced multiple times. I even created a new card in FPP to start over. There is nothing else anyone can think of -- other than pixel data being sent from some sequences that might be cached/leftover/hidden?? It's always the left arm and always to the same position.

![santa arm](https://github.com/FalconChristmas/fpp/assets/104024793/fce7e1c4-4b60-4c22-aed4-2e9328876926)

**Comment by McCoyCOREUSA** [comment] 2023-12-05 23:54
Here are the original and newly created welcome sequences. FYI

https://mccoycloud.com/index.php/s/wfsDcpWcKRCKJXK

**Comment by cpinkham** [comment] 2023-12-06 04:38
What channel in the sequence is for the arm?

**Comment by McCoyCOREUSA** [comment] 2023-12-06 15:15
Not sure what you are asking? 

The Servos are 9489-9512 (2 channels per servo). The left Arm servo that is activating is "LEFT Shoulder UP" and is servo channels 13 & 14 of that block of channels.

But, this servo is not programmed in the sequence. 

![2023-12-06_07-09-36](https://github.com/FalconChristmas/fpp/assets/104024793/5117f795-894d-41fb-927d-ba904e031549)

**Comment by McCoyCOREUSA** [comment] 2023-12-06 15:21
Sequence with no effects on the Left Shoulder UP servo....
![2023-12-06_09-21-10](https://github.com/FalconChristmas/fpp/assets/104024793/8d4cec44-5443-4f57-a351-ada2c09c74d5)

**Comment by McCoyCOREUSA** [comment] 2023-12-06 21:40
Today I planned on doing this with a new playlist. I'll let you know.

There is nothing else in the background/effects on my FPP. FYI

**Comment by McCoyCOREUSA** [comment] 2023-12-08 15:23
UPDATE
I created a new playlist (with a new name) and added the same sequences. I had zero issues in last night's show for the first time ever! Could there is something cached/stuck in FPP's playlists that is sending old sequence data???

**Comment by cpinkham** [comment] 2024-01-24 00:28
There is no channel data in playlists.  There is a chance this could have been related to duplicate packet detection on the E1.31 side.  I think a bug was fixed in this recently.  I'm going to close this ticket and it can be reopened if the problem shows up again.

**Closed by cpinkham** 2024-01-24 00:28 UTC
