### ISSUE TITLE
Sending commands via MQTT no longer works.

### ISSUE THREAD

**Issue by mover85** [FalconChristmas/fpp#1069] opened 2021-08-09 08:56 UTC
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 5.0 running on Docker

**Describe the bug and Steps to reproduce**: 
Sending any commands via MQTT using the /set/command topic no longer works. The message received on the topic does not show up in the logs. If I add falcon/player/HOSTNAME/set/command in the Subscribe Topic field in the MQTT settings it works.

**Expected behavior**: 
To be able to send commands via MQTT

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.
6. 
[FPP_Logs_20210809.0851.zip](https://github.com/FalconChristmas/fpp/files/6953123/FPP_Logs_20210809.0851.zip)

**Comment by patdelaney** [comment] 2021-08-09 12:37
For clarification does this only happen on Docker or can it be reproduced on PI or BBB?

**Comment by mover85** [comment] 2021-08-09 23:02
I haven't tested on a PI yet but I will try it soon.

**Comment by ghormann** [comment] 2021-08-09 23:51
I'm looking into this... I just cuased fppd to crash with a test of /set/command

**Comment by ghormann** [comment] 2021-08-10 00:59
OK, I found (and am fixing) a bug where if the JSON object supplied via the payload isn't a valid object, it would cause fppd to crash and restart.   This fix will be part of a future fpp release. 

However, when sending a properly formatted payload it works in my testing without doing the subscribe.     If you are still having  problems please do the following
1. Set Log level on "Command" to Debug
2. Provide the full payload you are using. 
3. Please provide the full topic name you are using.   It looks like you have the hostname configured as a FQDN.  I'm curious if you are using the FPDN or just the short name (fpp) when attempting to send the MQTT command.   

![image](https://user-images.githubusercontent.com/24968726/128792126-5dbfc850-da27-4448-8a74-1e6812221bb3.png)

**Comment by mover85** [comment] 2021-08-10 03:06
I was using the FQDN but have changed the hostname back to just fpp and it works.

**Comment by ghormann** [comment] 2021-08-13 22:41
In 5.0, it is no longer possible to provide a fully qualified domain via the UI.   Thus, I'm going to close this issue. 
![image](https://user-images.githubusercontent.com/24968726/129424621-57fd909d-89d3-4348-be77-4144780353a7.png)

**Closed by ghormann** 2021-08-13 22:41 UTC
Labels: Need Info
