### ISSUE TITLE
Raspberry Pi 4 not picking up NTP date/time

### ISSUE THREAD

**Issue by paulspann** [FalconChristmas/fpp#1956] opened 2024-09-05 07:53 UTC
FPP 8
FPP latest git version 1fd5cbc 

No hardware clock etc, just using NTP to get date/time.

Date time never updates when power up, used to be fine on 7
<img width="653" alt="Screenshot 2024-09-05 at 09 12 20" src="https://github.com/user-attachments/assets/8cf3782f-e975-4465-aa09-2de7566548b5">
<img width="1125" alt="Screenshot 2024-09-05 at 09 14 47" src="https://github.com/user-attachments/assets/0d709108-4d96-4361-9d31-b2d0548cb0ad">

[syslog.zip](https://github.com/user-attachments/files/16885857/syslog.zip)

**Comment by ghormann** [comment] 2024-09-05 08:47
I think the problem is that when manually setting the NTP Server it doesn't accept pools, only individual NTP servers.  I'm not sure if this is a bug or a feature, but I can reproduce it if I use a pool DNS record like you are doing.  That said, if I clear the field (leave it blank) it uses the default pool.

![image](https://github.com/user-attachments/assets/3a92954a-38dc-4ade-8413-f1be594a3119)

And per the trouble shooting guide it is working well now.

![image](https://github.com/user-attachments/assets/a6d4330c-fb6b-4985-bc88-95b57318fbbb)

**Comment by ghormann** [comment] 2024-09-05 08:50
This is how ntp.conf gets updated.  (It should be `pool` vs `server`.    I *guess* we could put some logic in to see if "pool" is part of the DNS name, but that isn't totally fool proof

![image](https://github.com/user-attachments/assets/2cddf11c-b6e7-4de8-8840-0c25ee4e4cab)

**Comment by darylc** [comment] 2024-09-05 09:46
Updated it to look like this 
![image](https://github.com/user-attachments/assets/6ece16ea-fffc-4f2a-a153-22b58a579f49)
We can always revisit next year if we really must support names.

**Comment by darylc** [comment] 2024-09-05 09:55
For the record, the only NTP related change in FPP v8 was to change the path to the debian config file which moved.  The use case of the custom NTP server setting in FPP is for those deployments that do not have internet connectivity.

**Comment by ghormann** [comment] 2024-09-06 00:35
CLosing this, replaced by #1958 (enhancement request to consider)

**Closed by ghormann** 2024-09-06 00:35 UTC
