### ISSUE TITLE
wifi password cannot contain a plus sign +

### ISSUE THREAD

**Issue by darylerwin** [FalconChristmas/fpp#474] opened 2018-12-04 13:34 UTC
We had a user on zoom that was stuck - couldnt change his router password but it contained a + sign. It wouldnt save that in the password. It was stripped out each time. This meant he couldnt get the wlan connection. We did come up with a workaround - created a guest SSID with a simple password.

**Comment by ghormann** [comment] 2019-03-03 14:39
It looks like this was fixed by bdaa1be0ba03528f45c0fc6f696751d1bc2cafdd. I believe this is Duplicate of #117 and should be closed

**Closed** 2019-04-12 23:07 UTC
