### ISSUE TITLE
v4 alpha ffpd stopped and wont restart

### ISSUE THREAD

**Issue by 1991mustang50** [FalconChristmas/fpp#694] opened 2020-04-01 02:01 UTC
i noticed that if Virtualdisplay is active and saved.  Upon restart/reboot ffpd will not restart until deactiving and saving and restart fppd. i have tried rebooting and even new and reflash image still not working. logs attached
[FPP_Logs_20200401.0140.zip](https://github.com/FalconChristmas/fpp/files/4412349/FPP_Logs_20200401.0140.zip)

**Comment by cpinkham** [comment] 2020-04-29 23:24
I am unable to reproduce this issue.  Can you update to the latest FPP v4.0-alpha3 SD image and without configuring anything else, add a Virtual Display and see if that fails?  if that doesn't, proceed with your other configuration changes and see where it stops working.

**Comment by cpinkham** [comment] 2020-05-01 20:43
Make that the 'v4.0-beta1' image....

**Comment by cpinkham** [comment] 2020-05-31 03:43
Closing unless someone reproduces the issue and can report details.

**Closed by cpinkham** 2020-05-31 03:43 UTC
Labels: v4.0
