### ISSUE TITLE
*Master Branch* - Everday Schedule with sunset/sunrise offset not running on Sundays

### ISSUE THREAD

**Issue by mararunr** [FalconChristmas/fpp#987] opened 2021-03-29 02:26 UTC
**FPP Version and Hardware**: 
Master FPP is Pi 3B+ running master branch (update every couple days - currently on 142)
Remotes 171-178 are all Pi Zero Ws running a mix of Master (114-142 currently) and 4.6.2
Remotes 181-183 are all Kulp F8-PBs running a mix of Master and 4.6.2
(remote numbers are my numbering - it's the last octet of the IP address just as FYI)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to Content Setup -->Scheduler
2. Set Schedule as Everyday, Sunset + 15min, and Sunrise -15min (any playlist)
3. See sequence running on house any night except Sunday

**Expected behavior**: 
Everyday schedule should play every day and not fail/skip on Sundays (has happened multiple Sundays now - thought it was me at first so waited a few weeks to see if it happened every Sunday)

**Additional context**: 
- Same controllers/setup/master/remotes as I used at Christmas but during Christmas I run different schedule on Fri/Sat vs Sun-Thu.
- This is a subset of controllers admittedly to Christmas but Master is master is master all year long.
- Nothing is connected to master (well no lights - master only runs audio broadcast however I do not play any audio sequences this time of year - only run audio for Halloween/Christmas/New Year)
- 171-178 are PiZeros sitting in Cans on the front of my house (down light cans that have been converted to be self-contained pixel down lights) and some of them are also running strings of lights on the corner of the house (25 in each can, max corner is 26 pixels)
- 181-183 are running flower bed lights, strings of pixels, a few spheres, window trim lights, etc.
- I have been using FPP since 2015  (Chris installed it for me at Expo in Fort Worth July 2015 and been hooked ever since)
- Schedule works fine the other 6 days a week (offset works, starts fine, stops fine, outside random times of the evening and never seen a problem)
- Only running a 30 second sequence only on loop all night

**Additional Attachments**
Attaching logs zip, happy to provide anything else you want

I can provide any screenshot you want.

[FPP_Logs_20210329.0208.zip](https://github.com/FalconChristmas/fpp/files/6218821/FPP_Logs_20210329.0208.zip)

**Comment by SmAsH-jl** [comment] 2021-03-29 16:01
I too had this happen yesterday. Had to start manually.  Also on master.

**Comment by mararunr** [comment] 2021-04-05 14:02
Ok, last night I sat and watched my phone when the everyday sequence was supposed to run on Sunday.  I took screenshots of the main page before, during, and after the time the sequence was supposed to run.  Sequence was supposed to start at 7:56, did not start during the 7:56 60 second period and then flipped to Monday start at the 7:57 time point without ever having started for Sunday.   I've also attached updated logs.  @cpinkham or @dkulp, any thoughts on what may be causing this?  Thanks, mv

[FPP_Logs_20210405.1358.zip](https://github.com/FalconChristmas/fpp/files/6258499/FPP_Logs_20210405.1358.zip)
![166991646_1860738837437883_9203003913563370884_n](https://user-images.githubusercontent.com/11252070/113582038-8076f700-95ed-11eb-9a34-3593b26b490e.jpg)
![167934953_252912236560296_4290367740528264304_n](https://user-images.githubusercontent.com/11252070/113582041-810f8d80-95ed-11eb-95ed-73ee111b0fd1.jpg)
![168975770_351058449670315_7314895157968040405_n](https://user-images.githubusercontent.com/11252070/113582042-810f8d80-95ed-11eb-962f-f231814f003d.jpg)
![166694756_749459789050869_7370537751668093134_n](https://user-images.githubusercontent.com/11252070/113582043-810f8d80-95ed-11eb-80ad-563814b44247.jpg)

**Comment by ghormann** [comment] 2021-04-05 22:30
@SmAsH-jl  can you upload your complete FPP_LOG_.*.zip file  (click "Download" on  Logs tab in File Manager).   This would be helpful.    I'm mostly curious to see what your schedule.json file looks like. 

This may require Chris to solve though...   He is the master of the scheduler code. :-)

**Comment by SmAsH-jl** [comment] 2021-04-06 05:53
> @SmAsH-jl can you upload your complete FPP_LOG_.*.zip file (click "Download" on Logs tab in File Manager). This would be helpful. I'm mostly curious to see what your schedule.json file looks like.
> 
> This may require Chris to solve though... He is the master of the scheduler code. :-)


![image](https://user-images.githubusercontent.com/3165913/113665026-0173d400-966a-11eb-90af-11adb63fe866.png)
[FPP_Logs_20210406.0551.zip](https://github.com/FalconChristmas/fpp/files/6262392/FPP_Logs_20210406.0551.zip)

PS.. happened again last night for me too. same thing. it acts like it's going to trigger.. then just skips to Monday. 
Screenshot of about screen and logs.zip Good luck guys

**Comment by cpinkham** [comment] 2021-04-06 06:22
I am looking into this.  Nothing stands out so far, so I'm going to add some debugging code and try to reproduce by setting the clock ahead on a test system.

**Comment by mararunr** [comment] 2021-04-12 21:45
Just FYI - same result last night (Sunday).  So that's 3 weeks in this ticket and at least 2 to 3 before.  I will say this was in place upgraded whenever that functionality came out if that matters maybe (not a scrubbed SD/clean install since in place upgrading became available - don't even remember what version that was now).

**Comment by cpinkham** [comment] 2021-04-12 22:42
I think this is a bug in the scheduler rewrite, I have started looking into it and testing some things, but haven't yet tracked down the issue.

**Comment by cpinkham** [comment] 2021-04-19 19:43
I tried this again on another system with the date set to a Sunday and the scheduled playlist fired correctly for me with both the Sunday and Everyday day settings.

On Saturday or Sunday prior to the Sunday scheduled start, can you turn your Scheduler logging up to the 'Excessive' level and then grab the logs zip again after the scheduled playlist does not start.  The log should show the scheduler counting down to the scheduled start and I'd like to see what is happening during that time as well as the additional detail about scheduled instances which are printed at the excessive level.  Once you grab the logs zip after the scheduled time passes, then you can set the log level back to Info.

**Comment by mararunr** [comment] 2021-04-28 18:09
[FPP_Logs_20210428.1807.zip](https://github.com/FalconChristmas/fpp/files/6393882/FPP_Logs_20210428.1807.zip)

@cpinkham I turned excessive logging on Friday (for Schedule) and off just now.  Hopefully I've captured what you need.  Thanks, mv

**Comment by cpinkham** [comment] 2021-05-10 00:01
Thanks, this log helped.  I can see that it did make it to the code that fires when the start time comes around, but it looks like one of the checks is failing and causing it to mark the item as already ran and continuing on.  I'm going to add some more debugging and try to reproduce again using a different test than I used last time and see if I can make it happen here to confirm.

**Comment by mararunr** [comment] 2021-06-02 14:38
Any update maybe @cpinkham ?  Thanks.

**Comment by mararunr** [comment] 2021-07-06 18:10
@cpinkham well positive side effect is my lights did not come on Sunday night (July 4th) and "ruin" the neighborhood fireworks :-).  (And yes I have now changed the sequence/playlist multiple times and still getting the bug with the schedule which I have not changed.)

**Comment by darylc** [comment] 2021-08-02 22:36
@mararunr Can you please re-test with the latest master?  Dan made some changes overnight.

**Comment by mararunr** [comment] 2021-08-03 02:22
@darylc I just updated master pi to latest master (was on 398, now on 419).  Still running exact same schedule from when I first reported issue so we will just wait until next Sunday to see if it runs or not (I didn't do any manipulation to find the bug so need to wait until Sunday to see if it happens again).  Thanks for the update!  mararunr (aka Mark Valentine)

**Comment by dkulp** [comment] 2021-08-08 14:56
I believe this is now fixed.

**Closed by dkulp** 2021-08-08 14:56 UTC

**Comment by mararunr** [comment] 2021-08-08 17:30
thanks.  my schedule doesnt come on until sunset tonight but I will definitely check.  thanks for fixing!

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 9:56 AM, Daniel ***@***.***> wrote:   


I believe this is now fixed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mararunr** [comment] 2021-08-09 02:32
worked just fine tonight.  thank you again!

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 9:56 AM, Daniel ***@***.***> wrote:   


Closed #987.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
