### ISSUE TITLE
FPP 6.0/6.0.2 audio issues with Sound Blaster 3

### ISSUE THREAD

**Issue by ChonLee** [FalconChristmas/fpp#1341] opened 2022-08-26 01:23 UTC
FPP 6.0/6.0.2 running on RP4 2GB and also on Compute Module 4 8GB 32GB MMC with Raspberry Pi Foundation IO board.

**Describe the bug and Steps to reproduce**: 
When playing a sequence or only an audio file on FPP6 via the Creative Sound Blaster 3 USB, the audio is popping and scratchy.

**Expected behavior**: 
Audio should be rendered like the original file.

**Additional context**: 
The noises are compounded when using USB2 on both RP4 and CM4.  When I switch to USB3 on the RP4 the noise still exists but is reduced in how often it happens. 

When I return to FPP 5.5 the problem no longer exists.

**Additional Attachments**
[FPP_Logs_20220826.0121.zip](https://github.com/FalconChristmas/fpp/files/9429083/FPP_Logs_20220826.0121.zip)

**Comment by ChonLee** [comment] 2022-08-28 21:02
Was able to test on 3B+ on 6.0.2 and am also experiencing the same issue.

**Comment by bloojoop** [comment] 2022-08-29 18:49
I can also reproduce this poor quality sound issue with FPP 6.x on K8-b and k4-pb with sound blaster 3.  We have also heard this issue with K16 onboard audio as well,  Here is a log from my k4 that I forwarded before. 
[k4_fpp6_audiostatic_issue.zip](https://github.com/FalconChristmas/fpp/files/9447140/k4_fpp6_audiostatic_issue.zip)

**Comment by ThunderBunny79** [comment] 2022-08-29 22:04
Same issues using Kulp K8 on FPP 6.  Backed down to 5.5 and fixed the issue.

**Comment by andyaz** [comment] 2022-09-01 02:28
I have noticed the same thing on Pi3b and Pi3b+ with SB3 on 6.0.2. Audio sounds distorted or poppy almost like overdriven.

**Comment by dkulp** [comment] 2022-09-01 10:07
If some folks could try flipping to master branch and testing there (will need reboot after moving to master), I'd really appreciate it.

**Comment by andyaz** [comment] 2022-09-03 22:01
Rolled the master FPP to the master branch 17af020 and quick initial testing seems to have better audio quality. I will run it more with more audio tracks still today to get a better idea.
Anyone else able to weigh in?

**Comment by andyaz** [comment] 2022-09-04 05:01
Additional testing this evening and the audio seems to be much improved. I think your audio buffer size increase was the fix for my case. We will see if anyone else weighs in on it.

**Comment by kevinsaucier** [comment] 2022-09-04 16:58
I know this issue names the SB3 specifically but a comment above says they heard the same issue with the onboard audio so figured I'd throw my hat in the ring here.  I've had bad static since upgrading.  Also have an ongoing issue where the Audio Output/Device will go to 'Dummy' after a restart.  The davinci card is in the list, but it defaults to Dummy.   I can switch it, then reboot, and then it holds davinci while running, but another restart or power off typically causes it to go back to Dummy.

I just jumped over to Master on my K32 using the (Vast/Kulp add on board) and it's fully up to date but I'm still getting a ton of static, both locally as well as across the FM transmitter.  Also, the song that's playing keeps slowing down and speeding back up, like it's overloaded and struggling to keep up.  Just looked at the LCD on the board and it's bouncing between showing the sequence that's playing and showing the 'Kulp Lights' logo screen with a line that says FPPD is not running (even though it obviously is as the sequence continues playing). 

6.x-master-561-g17af020f
[FPP_Logs_20220904.1655.zip](https://github.com/FalconChristmas/fpp/files/9485107/FPP_Logs_20220904.1655.zip)

**Comment by emarti20** [comment] 2022-09-05 20:37
Fresh install of the 6.0.2 image on a K8-PB with an SB3 and noticed the scratchy audio as well.  I'm also noticing the same as Kevin above in that the audio and sequence seem to ebb and flow in speed.  I ran a stopwatch against a sequence and it ran about 10 seconds longer in real time that the sequence.  If I change the playlist to play something as sequence only, it runs for the correct time.

I've also seen the SB3 disappear and FPP will report that it's switched to Dummy for audio output and then a reboot will bring it back.  If there is any particular logging that would be helpful, let me know what section and what level.  I tried setting MediaOut to excessive and that's showing it taking about 1.1 seconds per reports second of audio output.  No errors or anything else of significance in there though.

**Comment by jeffbmiller** [comment] 2022-09-10 01:11
I am having the same problem on my kulp PB-8 with Soundblaster 3.  I will try checking out master branch and see if it is any better.

**Comment by jeffbmiller** [comment] 2022-09-10 01:25
Just tested with Master.  Audio is sounding great again!

**Comment by dkulp** [comment] 2022-10-04 14:02
Fixed in 6.1

**Closed by dkulp** 2022-10-04 14:02 UTC
