### ISSUE TITLE
Log messages for review (Potentially suspicious?)

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#907] opened 2020-12-06 06:42 UTC
Beaglebone Black w/ F32-B Version 2.0 and VAST FM Transmitter connected
FPP Version v4.5.1-5-g1f787185

Not sure if this is a bug but I see this in the logs fairly often and from time to time my audio just stops working. Not sure if the two are related:

In the fppd log:
2020-12-05 18:11:41.482 (2039) fseq/FSEQFile.cpp:493: VariableHeader sp data exceeds header buffer size!2020-12-05 18:54:18.655 (2039) fseq/FSEQFile.cpp:493: VariableHeader sp data exceeds header buffer size!2020-12-05 19:36:55.711 (2039) fseq/FSEQFile.cpp:493: VariableHeader sp data exceeds header buffer size!2020-12-05 20:19:32.853 (2039) fseq/FSEQFile.cpp:493: VariableHeader sp data exceeds header buffer size!2020-12-05 21:00:00.009 (2039) Scheduler.cpp:718: Schedule Entry: 17:38:00 - 21:00:00 - Stopping Playlist Gracefully
2020-12-05 21:06:42.280 (2039) fseq/FSEQFile.cpp:493: VariableHeader sp data exceeds header buffer size!2020-12-05 21:06:42.293 (2039) fppd.c:225: Crash handler called:  11
2020-12-05 21:06:58.764 (2039) fppd.c:209: Stack: 

In var/log/messages:
Dec  5 22:34:45 fppgrnd1 kernel: [   42.023276] usbhid: USB HID core driver
Dec  5 22:34:46 fppgrnd1 kernel: [   42.672301] usb 1-1: current rate 895258 is different from the runtime rate 44100

I've attached all my logs for further review:
[FPP_Logs_20201206.0641.zip](https://github.com/FalconChristmas/fpp/files/5648385/FPP_Logs_20201206.0641.zip)

**Comment by letsrollusafa11** [comment] 2020-12-06 15:20
To add, I'm also having this issue. Whenever SoundBlaster3 USB device is plugged in for audio out the sequence dies mid song. 

2020-12-05 20:29:34.870 (2724) mediaoutput/SDLOut.cpp:264: Stalled audio, buffers still filling.                                                                                                                   
2020-12-05 20:29:34.870 (2724) mediaoutput/SDLOut.cpp:264: Stalled audio, buffers still filling.                                                                                                                   
2020-12-05 20:29:35.382 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:36.312 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:37.202 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:38.133 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:39.013 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:39.932 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:40.833 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:41.763 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:42.653 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:43.579 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:46.513 (2679) fppd.c:683: Shutting down main loop.

**Comment by patdelaney** [comment] 2020-12-06 15:42
Is it the same audio clip that generates this error or random ones?
What bitrate are the audio files encoded at?
To possibly preproduce the issue we may need the audio files.

**Comment by letsrollusafa11** [comment] 2020-12-06 15:47
Not to hijack the original poster. Random songs. I'd have to look into the bitrate.

**Comment by nmiller0113** [comment] 2020-12-06 18:10
@letsrollusafa11 your issue is related to mp3 tag's. You can use mp3tag to remove and re-add the minimum tag (artist/title) and that will remove those errors. It shouldn't cause any playback issues though. As far as audio stopping, mine is very, very, very few and far between and mine runs music 24 hours a day, and I don't have any of the same errors you're seeing. I was mainly posting the VariableHeader sp error, which I just found is reported in another bug which I'll start commenting on there. That leaves me with the USB messages I get from time to time - Dec 5 22:34:46 fppgrnd1 kernel: [ 42.672301] usb 1-1: current rate 895258 is different from the runtime rate 44100. I'm not sure that if it's actually a bad thing or just informational, and this is what I'm trying to confirm in case it is related to my audio dropping the 2 times in 3 weeks that it has.

**Comment by nmiller0113** [comment] 2020-12-06 22:57
@letsrollusafa11 my bad. I read your message in a hurry earlier today and just now realized you were sharing the tags with the data. My apologies :)

There had been others in the past with those messages popping up in the logs with errors, and I thought at a glance that was what you were sharing.

**Comment by darylc** [comment] 2023-01-25 06:03
audio looks to be duplicate of an older closed issue, : VariableHeader sp data exceeds header buffer size is duplicate of issue #886

**Closed by darylc** 2023-01-25 06:03 UTC
