### ISSUE TITLE
Add start time parameter to startPlaylist REST method

### ISSUE THREAD

**Issue by idleup** [FalconChristmas/fpp#485] opened 2018-12-20 20:23 UTC
I like how fppjson has a start time parameter for the startSequence method. Can that same functionality be added to the startPlaylist REST method?

**Comment by cpinkham** [comment] 2020-12-02 05:06
Duplicate of #765 

I looked into this after reading #765.  I think this may be workable but would require a bit of work.  Leaving the other ticket open as I'd like to readd the functionality.

**Closed by cpinkham** 2020-12-02 05:06 UTC
