### ISSUE TITLE
Enhancement: Export / Import Email settings

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#114] opened 2014-10-27 03:28 UTC
As a user I would like the ability to Export Email settings and be able to import it on to another FPP.
I have 6 FPP and I don't want to have to type the email configs over again on each unit.

Thanks

**Comment by jaredb7** [comment] 2015-05-14 21:39
Expanding on this idea it would be good to have the ability to export all the settings from FPP, for backup and for cloning into to another FPP. 

I have some ideas on this and if I get some time I'll see what I can do.

**Comment by cpinkham** [comment] 2015-08-08 08:29
Closing this as a duplicate of #146 since that ticket will cover backing up and restoring config files and allow selection of what to backup and restore.

**Closed by cpinkham** 2015-08-08 08:29 UTC
