### ISSUE TITLE
Option for 2.4Ghz and 5Ghz for WiFi

### ISSUE THREAD

**Issue by datcomputerguy** [FalconChristmas/fpp#1198] opened 2021-12-11 18:37 UTC
**Is your feature request related to a problem? Please describe.**
Added option to force your WiFi dongle to connect to the 5GHz or 2.4Ghz version of a particular SSID.

**Describe the solution you'd like**
A checkbox, drop down, whatever with the options for WiFi interfaces with dual band capabilities:
- Auto
- 2.4GHz Only
- 5GHz Only

**Describe alternatives you've considered**
You can set these parameters in the OS but since FPP reloads and sets these each time it loads, the config settings are lost.

**Additional context**
I use a UniFi system and was having issues when the AP system decided to push one of my FPP devices from 5GHz to 2.4GHz.  In theory the driver should be able to handle this, but something funky was happening and the device would show as connected to my WiFi but I was unable to ping or access it.  The device in question is across the street from me, so 2.4GHz makes more sense than 5GHz.  But I made a work around where I made a dedicated 2.4GHz SSID to connect this problem device to, but it would be nice to just have an option to force it on the FPP instance if needed.

**Comment by cpinkham** [comment] 2021-12-14 07:58
Closing as duplicate of #1166.

**Closed by cpinkham** 2021-12-14 07:58 UTC
Labels: enhancement
