### ISSUE TITLE
V8 Channel Output - LED Panels - Test Pattern

### ISSUE THREAD

**Issue by bobreese** [FalconChristmas/fpp#1976] opened 2024-09-16 20:39 UTC
Pi4 Gig connection to Colorlight card and P10.
Using the Test Pattern for LED Panels starts the pattern test, when stopping the test, the P10 stops flashing but the test pattern stays on.
Video added to help understand.
[P10Test.zip](https://github.com/user-attachments/files/17019658/P10Test.zip)

**Comment by patdelaney** [comment] 2024-09-16 22:05
I am able to reproduce this on Pi V8 release.
I am **not** able to reproduce on BB based capes

**Comment by Poporacer** [comment] 2024-09-23 03:03
I am not able to reproduce on current V8-4. Can you upgrade and see if the problem persists?

**Comment by patdelaney** [comment] 2024-09-25 10:25
I have 2 pi 3, that I was able to reproduce the issue. Both were fppos upgraded. This morning I burned a fresh image of FPPV8 and tested it and I could hit the test button the test image flashed on the panels and I hit stop and the image disappeared and the panel blanks,  I flipped to Master branch and updatd to latest master and the test button works as expected. 

I'mnot sure where the problem is.

**Comment by Poporacer** [comment] 2024-10-01 04:03
This was tested on several Pis, 3B+ and 4 and none of them had this issue. I suggest we close this.

**Closed** 2024-10-01 04:03 UTC
