### ISSUE TITLE
FPP 4.0 FPPD Crashing

### ISSUE THREAD

**Issue by agent462** [FalconChristmas/fpp#758] opened 2020-07-21 21:46 UTC
I can recreate this every single time:

Pi4
Xlights 2020.28

1. Format SD Card
2. Burn FPP-v4.0-Pi.img
3. Boot and then update to v4.0.1
4. Go to xlights and FPP Connect
5. Upload Sequence
6. Changes detected, restart fppd
7. Crash Loop

Jul 21 22:41:17 FPP systemd[1]: Stopped FPPd.
Jul 21 22:41:17 FPP systemd[1]: Starting FPPd...
Jul 21 22:41:17 FPP fppd_boot_pre[3870]: Setup channel outputs
Jul 21 22:41:17 FPP fppd_boot_pre[3870]: Running pre-start scripts
Jul 21 22:41:17 FPP fppd_boot_pre[3870]: FPP - Turning OFF screen blanking
Jul 21 22:41:17 FPP kernel: [  379.341090] i2c i2c-1: Failed to register i2c client lm75 at 0x48 (-16)
Jul 21 22:41:17 FPP fppd[3892]: terminate called after throwing an instance of 'std::invalid_argument'
Jul 21 22:41:17 FPP fppd[3892]:   what():  stoi
Jul 21 22:41:17 FPP fppd[3892]: Magick: abort due to signal 6 (SIGABRT) "Abort"...
Jul 21 22:41:17 FPP systemd[1]: fppd.service: Main process exited, code=killed, status=6/ABRT
Jul 21 22:41:19 FPP systemd[1]: fppd.service: Failed with result 'signal'.
Jul 21 22:41:19 FPP systemd[1]: Failed to start FPPd.

**Comment by agent462** [comment] 2020-07-21 21:52
[FPP_Logs_20200721.2152.zip](https://github.com/FalconChristmas/fpp/files/4956457/FPP_Logs_20200721.2152.zip)

**Comment by mghaff007** [comment] 2020-10-04 03:09
I as well have the exact same issue. Could it be with xlights? I am going to try and reinstall FPP and try to manually upload my files to FPP from xlights.
[FPP_Logs_20201004.0306.zip](https://github.com/FalconChristmas/fpp/files/5322612/FPP_Logs_20201004.0306.zip)

**Comment by dkulp** [comment] 2020-10-04 04:29
@mghaff007 Your model-overlays contains a model named "Custom" which has 0 channel count and 0 channels per node.   Not sure how that was created in xLIghts, but that's definitely the one causing your crash.

**Comment by mghaff007** [comment] 2020-10-04 15:51
OMG. That is so right! Now I feel so stupid. I was working on a face.

Thank You dkulp!

**Comment by ghormann** [comment] 2020-10-06 23:51
You should just be able to delete the model and click the restart fppd using the button on the website.   I'm going to close this issue as it was caused by a bad model.

**Comment by agent462** [comment] 2020-10-07 00:21
That was the issue with his but does that answer the original issue?

**Comment by ghormann** [comment] 2020-10-07 00:27
The original issue is a crash loop.  It explains that.  I'm not sure how the empty model overlay was created.   Do you know how to reproduce that?

**Comment by darylc** [comment] 2021-06-20 02:11
should we close this one given the lack of updates/information @ghormann ?

**Comment by ghormann** [comment] 2021-06-20 02:20
Closing. Will reopen if method for reproducing empty model is reported.

**Closed by ghormann** 2021-06-20 02:20 UTC
