### ISSUE TITLE
BBB Jessie /etc/fstab not uncommented when you select usb stick for storage in fpp settings.

### ISSUE THREAD

**Issue by patdelaney** [FalconChristmas/fpp#230] opened 2016-06-17 02:47 UTC
The BBB on 2.0 o/s image and master branch does not actually uncomment the /etc/fstab file so that you can use the USB stick. You have to manually edit the file and reboot.

The issue with selecting the USB stick for storage seems to also be an issue when you install the eMMC image to the BBB and then try to select the SD card for storage. Instead of USB stick.

Pat

**Comment by cpinkham** [comment] 2016-06-23 15:51
Duplicate of #227.

**Closed by cpinkham** 2016-06-23 15:51 UTC
