### ISSUE TITLE
Confusion of OS Version and if an upgrade is actually available.

### ISSUE THREAD

**Issue by WayneHancock** [FalconChristmas/fpp#1169] opened 2021-11-26 20:06 UTC
![FPP OS Upgrade Screen](https://user-images.githubusercontent.com/30911215/143625847-9b9a9ac2-e8ed-43fa-ac1f-96dfafa3ed2b.png)

The attached photo seems to indicate that the OS version should be 5.4.1, and has an upgrade button next to it.
However, apparently the latest FPP OS version is 5.3.  This is confusing as it would seem to be indicating that there IS a FPP OS update, when there isn't.

Can this be made more clear for those OCD of us that want to make everything match if we can? :-)

**Comment by kriskirkland** [comment] 2021-11-30 17:57
Same here, keeps saying OS build is 5.3 and the upgrade appears to happen. I hope its just a UI issue.

**Comment by kriskirkland** [comment] 2021-11-30 18:18
So after a little searching I found a closed ticket with the following info from @ghormann ; 

> Thanks for reporting. There were no OS changes between 5.3 and 5.4.1 just changed to fpp code. Thus running 5.4 or 5.4.1 will report an OS of 5.3

**Comment by msimmons78** [comment] 2021-11-30 18:22
Is this accurate info?

**Comment by nmiller0113** [comment] 2021-11-30 18:45
It's been this way for some time. If there are no underlying OS changes, kernel, driver updates, patch or package updates...etc, then the OS version remains the same. The FPP version is intentionally separate so we can differentiate between the two. This really helps in identifying folks who didn't do a full re-image or in place OS Upgrade when updating FPP. This is why this is stated in the release notes for each version as you could be running an OS version that doesn't support newer FPP features:

> For users of FPP 4.x or older, it is strongly recommended to do a full "OS Level" upgrade or re-image instead of attempting to upgrade directly from any older FPP version. There are several new features that will not work if an OS level upgrade is not done. There are two ways to do so:
Re-image - you can backup your 4.x configuration, create a new image, and restore the configuration.
In-place upgrade - this is new and requires you to have FPP 3.6.2 (or 4.0-alpha2) or newer already running on the device. Download the appropriate "fppos" file to your computer. Make sure the file extension is still fppos (some browsers will rename it). Upload it to the "File Manager" on the FPP instance. Then go to the about page. Under the normal "Manual Upgrade", a new Upgrade OS button should appear. Click it and wait a LONG time. When done, it should reboot into 5.0. At that point, go to the Uploads tab of the FPP File Manager and delete the fppos file. Note: In SOME cases, the reboot will fail due to library replacement. In that case, a power cycle may be required to get it back up and running.

**Comment by dkulp** [comment] 2021-11-30 18:55
I think next year, the OS level will become a y/m date stamp (2021-08) or something that is unique from the FPP version.

**Comment by WayneHancock** [comment] 2021-12-01 04:40
I think that as long as they are the same format... confusion will occur when there is a button to the right with "UpgradeOS".

Can the upgrade buttons not show up if there is no upgrade to be found? :-)

**Comment by ptr727** [comment] 2021-12-11 01:40
Concur, this also confused me, I tried to upgrade to get OS Build to match Upgrade OS, but the version is not the same.
Would be great if versions matched, and / or a flag showing FPP latest, OS latest.
E.g. I found that even burning a fresh SD card, and doing an update, still performed an update, don't know if the update script blindly runs the submodule updates, or if the flashed image is actually out of date?

**Comment by artwait** [comment] 2021-12-19 19:17
Yep. Confused by it also. The implication when I see "Pa-5.4.1.fppos" next to the "Upgrade OS" button--which is separate from the "Upgrade FPP" button--is that the current OS version is 5.4.1 and an OS upgrade is available. This may be working as intended, but it is a bit of a usability issue.

**Comment by artwait** [comment] 2021-12-20 16:21
Makes sense. Sounds like a lot of work to address this. If the release
notes provide this info (ie, whether a release contains a new OS), perhaps
a help bubble with a note that not all upgrades require usage of this
button and a link to the release notes index, could alleviate confusion.

Another option might be a console output line at the end of the install
process saying something like, "you're all up to date, no further action
required." (assuming the install script can determine this).

Thanks!

**Comment by cpinkham** [comment] 2022-06-17 02:03
Closing this as complete, the OS version is now based on the year so the OS and FPP versions no longer coincide.

**Closed by cpinkham** 2022-06-17 02:03 UTC
