### ISSUE TITLE
FPPDWatcher script no longer working in last update

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#595] opened 2019-11-18 04:54 UTC
Im on  v3.x-master-197-g117d8959 and one of the last few updates caused the FPPDWatcher script to stop working. I have it loaded and its running using the callback hook, I used to be able as a test to manually stop fppd and pithing 30 seconds it auto started back up, this no longer happens, I hit stop and it stays stopped

**Comment by cpinkham** [comment] 2019-11-20 07:50
I have a Pi running the v3.5.1 SD image and v3.x-master-201-gd381ebc3 and am unable to reproduce this.  Can you restart fppd, ssh into the Pi, and try killing fppd manually using "killall -9 fppd" and see if fppdWatcher restarts it correctly?

We probably need to modify the script to use systemctl to restart fppd now as well since Dan discovered an issue with calling fppd_start directly on the BBB.

**Comment by Vlad-Star** [comment] 2019-11-20 12:16
I am seeing the same behavior at least since 3.4.2. Upgraded to 3.5.2 yesterday, but the issue is still there.

Steps to reproduce: 
1) Install fppdWatcher.sh from the Script Repository (do NOT install fppdWatcherStart.sh)
2) Run the script from the UI. It detects its own forked processes, but not the state of the fppdWatcher.sh process that supposed to be running in a memory and quits without any action, regardless of the state of fppd.

I  added some debug lines to the script, here is the output (see "OTHERPID" value):

DEBUG: BASE=$(basename $0)
DEBUG: BASE value: fppdWatcher.sh
DEBUG: OTHERPID=$(ps -edaf | grep fppdWatcher.sh | grep -v grep | grep -v  $$  | awk '{print $2}')
DEBUG: $$ value: 31932
DEBUG: OTHERPID value: 31926
31927

The fppdWatcher.sh script is already running as PID 31926
31927

--- DEBUG: current list of processes: ---
UID        PID  PPID  C STIME TTY          TIME CMD
[...]
fpp      31926 31535  0 13:41 ?        00:00:00 sh -c sudo /opt/fpp/scripts/eventScript /home/fpp/media/scripts/fppdWatcher.sh 
root     31927 31926  0 13:41 ?        00:00:00 sudo /opt/fpp/scripts/eventScript /home/fpp/media/scripts/fppdWatcher.sh
root     31932 31927  0 13:41 ?        00:00:00 /bin/bash /home/fpp/media/scripts/fppdWatcher.sh
root     31951 31932  0 13:41 ?        00:00:00 ps -edaf
---
As a workaround, I added "grep -v eventScript" to "OTHERPID=..." line

**Comment by bchiaino** [comment] 2019-11-20 12:25
> I have a Pi running the v3.5.1 SD image and v3.x-master-201-gd381ebc3 and am unable to reproduce this. Can you restart fppd, ssh into the Pi, and try killing fppd manually using "killall -9 fppd" and see if fppdWatcher restarts it correctly?
> 
> We probably need to modify the script to use systemctl to restart fppd now as well since Dan discovered an issue with calling fppd_start directly on the BBB.

yeah this started happening in the last master update a few days ago Chris, 3.5.1 it was working fine for me

**Comment by bchiaino** [comment] 2019-11-20 12:44
correct me if im wrong case I did this a while ago but the way I always did it unless it has changed recently is download fppdwatcher and usercallbackhook, in user callback I add the following and reboot, I confirm fppdwatcher is now running but if I hit "stop" it never restarts like it used to in previous versions

![Screen Shot 2019-11-20 at 7 40 50 AM](https://user-images.githubusercontent.com/40632971/69239992-817ac600-0b69-11ea-9484-87b3493c7213.png)

**Comment by bchiaino** [comment] 2019-11-20 12:55
maybe the "use restart" update Dan pushed is what broke it somewhere?

https://github.com/FalconChristmas/fpp/commit/f3d94c33ef55b1d3aa7968d8d2fc77bf70918ac2

**Comment by cpinkham** [comment] 2019-11-21 05:27
I'm unable to reproduce the primary issue noted in the ticket.  I started fppdWatcher.sh using the fppdWatcherStart.sh script which is the same nohup command that you have in your callback script.  I can kill fppd from the command line  using "sudo killall -9 fppd" and also stop it from the FPP UI using the stop button and fppdWatcher.sh always restarts fppd.

@Vlad-Star you can not run the current (now previous) version of fppdWatcher.sh from the FPP File Manager because it does use the eventScript wrapper, but I just pushed a fix to add the "grep -v eventScript" to the script which should allow it to work.  It wasn't originally intended to be run that way, but there's no reason not to allow it so that was a good catch, thanks.

**Comment by bchiaino** [comment] 2019-11-21 12:06
Chris are you using 3.5.2 or 1? It works fine there. Once I switch to master branch is where all 3 of my pis stop working with it

**Comment by bchiaino** [comment] 2019-11-21 13:09
> I'm unable to reproduce the primary issue noted in the ticket. I started fppdWatcher.sh using the fppdWatcherStart.sh script which is the same nohup command that you have in your callback script. I can kill fppd from the command line using "sudo killall -9 fppd" and also stop it from the FPP UI using the stop button and fppdWatcher.sh always restarts fppd.
> 
> @Vlad-Star you can not run the current (now previous) version of fppdWatcher.sh from the FPP File Manager because it does use the eventScript wrapper, but I just pushed a fix to add the "grep -v eventScript" to the script which should allow it to work. It wasn't originally intended to be run that way, but there's no reason not to allow it so that was a good catch, thanks.

Chris now that I installed the new script, when I hit "stop fppd" it stops the watcher from running altogether and never starts fppd back up, I screen recorded and explained here if you're interested in seeing, thanks for your help! https://youtu.be/yxJkxVUOx_E

**Comment by cpinkham** [comment] 2019-11-21 18:27
The new script should not have affected the watcher restart ability at all, the only thing it affected was to allow the watcher to be started via the File Manager which runs scripts using the eventScript wrapper script.

I have a Pi running the v3.5 SD image and the master code branch.

v3.x-master-209-g6587dd37 (master branch)

I just installed fppdWatcher.sh and fppdWatcherStart.sh for the first time on this particular Pi.  After installing, I went to the File Manager and ran fppdWatcherStart.sh to start fppdWatcher.sh.  I then went to the status page and clicked the 'Stop FPPD' button.  FPPD stopped and within 30 seconds, fppdWatcher.sh restarted fppd.

I have another Pi that I need to upgrade from a v2.x image.  I downloaded the v3.5.2 SD image and plan to put that on this Pi to test.

**Comment by nmiller0113** [comment] 2019-11-21 18:42
@cpinkham @dkulp @bchiaino - I've been following this thread and was curious why this is needed.  I get the purpose of the script but shouldn't FPPD stopping on its own be a sign that something isn't working as it should and needs to get checked out?  I've been running FPP for 3+ years and never had to use this or ever really had problems with FPPD stopping randomly on its own.

I'm curious if there is a plan to integrate this into FPP as standard type of watchdog service that will monitor for critical service failures to restart them automatically.  Then, also, log the failure and trigger some sort of alert so that there is knowledge of it for investigation.  I'm only asking as I'm assuming, since I've never had to use it, that with this script there is no alerting, just an automatic restart if the FPPD service has failed, and I would have zero knowledge there is a problem under the hood.  This is obviously more a question for @cpinkham and @dkulp.

**Comment by cpinkham** [comment] 2019-11-21 18:56
@nmiller0113 This question comes up every so often.  To me is is a simple insurance policy.  I normally run bleeding edge master branch code on my production systems so that I can be the guinea pig or canary in the coal mine for issues.  If there are bugs which cause crashes, some of these issues might be reproducible and could cause fppd to repeatedly crash, but some might be random and the simple fppdWatcher.sh script restarts fppd and the folks sitting out front of the house watching are somewhat happy.  Now that we are using systemctl, there could be better ways to accomplish this.  Another one of the ideas tossed around a year or two ago was to have a C++ daemon wrapper that was just a watchdog and would be responsible for starting/stopping/restarting the backend fppd daemon that did all the work.  This could also allow us to separate out some of the light-delivery functions from some of the other parts of fppd.  Due to my limited development time though, this is way down the list of priorities for me and fppdWatcher.sh does what I want it to do.

@bchiaino I watched the videos.  Are you certain that fppdWatcher.sh is actually running after the switch to the master branch and reboot?  I didn't see that in the video, as soon as the Pi rebooted, you stopped fppd and it didn't restart.  The "grep -v eventScript" should not have any effect on stopping fppd, that addition only allowed the fppdWatcher.sh script to be started via the eventScript wrapper.  Prior to the addition of that grep, the OTHERPID check at the top of the script would see the eventScript wrapper running and prevent fppdWatcher from running since it thought that it was already running when in reality the eventScript wrapper was just the parent process of the fppdWatcher that was trying to start.

**Comment by nmiller0113** [comment] 2019-11-21 19:25
@cpinkham - makes sense, thank you for the detailed reply.  How hard would it be for someone to modify the script to email when it actually has to trigger a restart?  I'm assuming that all I'd need to do is setup the email config in FPP for this to work.  Just for general awareness so I know when to check into what is causing the failures.  I'd do it myself but unfortunately scripting is not my expertise.

**Comment by dkulp** [comment] 2019-11-21 21:06
@cpinkham If we change the "fppd" systemd service to start the fppd executable directly instead of the scripts, then systemd can handle the restart automatically.   You can add a Restart=on-failure flag to the service description and it would handle it completely.  The problem is your insistence on being able to run from someplace other than /opt/fpp.

**Comment by bchiaino** [comment] 2019-11-21 23:21
> @nmiller0113 This question comes up every so often. To me is is a simple insurance policy. I normally run bleeding edge master branch code on my production systems so that I can be the guinea pig or canary in the coal mine for issues. If there are bugs which cause crashes, some of these issues might be reproducible and could cause fppd to repeatedly crash, but some might be random and the simple fppdWatcher.sh script restarts fppd and the folks sitting out front of the house watching are somewhat happy. Now that we are using systemctl, there could be better ways to accomplish this. Another one of the ideas tossed around a year or two ago was to have a C++ daemon wrapper that was just a watchdog and would be responsible for starting/stopping/restarting the backend fppd daemon that did all the work. This could also allow us to separate out some of the light-delivery functions from some of the other parts of fppd. Due to my limited development time though, this is way down the list of priorities for me and fppdWatcher.sh does what I want it to do.
> 
> @bchiaino I watched the videos. Are you certain that fppdWatcher.sh is actually running after the switch to the master branch and reboot? I didn't see that in the video, as soon as the Pi rebooted, you stopped fppd and it didn't restart. The "grep -v eventScript" should not have any effect on stopping fppd, that addition only allowed the fppdWatcher.sh script to be started via the eventScript wrapper. Prior to the addition of that grep, the OTHERPID check at the top of the script would see the eventScript wrapper running and prevent fppdWatcher from running since it thought that it was already running when in reality the eventScript wrapper was just the parent process of the fppdWatcher that was trying to start.

yes it was running. If I hit stop if kills fppdwatcher but if I suds command killall in SSH then it stops fppd and restarts within 30 seconds. this is one failing if I press stop as a test which worked in prior builds

**Comment by bchiaino** [comment] 2019-11-22 15:39
And this is why its so important for this, I came home this morning and FPPD was stopped at like 9am for no reason. I checked and watcher was running but fppd has been stopped for over an hour :(

![Screen Shot 2019-11-22 at 10 38 25 AM](https://user-images.githubusercontent.com/40632971/69439168-64cec180-0d14-11ea-9b84-b324a101077f.png)
![Screen Shot 2019-11-22 at 10 37 39 AM](https://user-images.githubusercontent.com/40632971/69439169-64cec180-0d14-11ea-80d5-090edae82fe0.png)

**Comment by cpinkham** [comment] 2019-11-22 21:08
> @cpinkham If we change the "fppd" systemd service to start the fppd executable directly instead of the scripts, then systemd can handle the restart automatically. You can add a Restart=on-failure flag to the service description and it would handle it completely. The problem is your insistence on being able to run from someplace other than /opt/fpp.

I can work around any issue that might arise, so if you want to make it work this way, that is fine with me calling /opt/fpp/src/fppd directly from systemctl.  I don't use systemctl or fppd_start on my main Fedora dev system, but do on the Pi's and BBB's I have setup for dev.

**Comment by cpinkham** [comment] 2020-04-29 23:33
fppdWatcher is not needed for FPP v4.0 since we spawn fppd from systemd.  Closing ticket since we likely won't dedicate time to fixing things for older FPP versions.

**Closed by cpinkham** 2020-04-29 23:33 UTC
