### ISSUE TITLE
Multisync.php stops responding on RasPi 3 

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#283] opened 2017-10-06 19:53 UTC
Running v1.9-64-g01a089f on all three. They are all connected via wlan0 using a Static IP. There is no CAT5 connection. 

After "a period of time" they stop being visible to my FPP Master (which is a Pi 2B), They are fully accessible by their IP addresses but will not even display Multisync data on their own pages. 

I have found that going to their Network page and Refreshing the network always brings them back to full function immediately (but not permanently). 

This has happened repeatedly but only on RasPi 3 models. This is being discussed on the Falcon Forum also.

**Comment by patdelaney** [comment] 2017-10-29 14:36
I have a similar issue on a Pi B running Jessie and master v1.x branch. When I go to multisynch tab it eventually times out and can't get the status or a unit. I have a mixture of B, B+ V2, and V3. All are currently in standalone mode. I have seen it fail to discover v2 and v3. I can open the multisync page on another model B running Wheezy 1.9 and the page dispays fine, no issues.
![multi-synch_error](https://user-images.githubusercontent.com/8147459/32144829-9d74e404-bc8c-11e7-8ea8-d4c1312eb07d.jpg)

**Comment by jaredb7** [comment] 2018-03-12 13:25
@patdelaney would you happen to have the log files from this install at all? Mainly the apache2-error.log from the /logs directory on the USB stick 
I just want to see what's causing the Get Status Failed error, I run some of my FPP's with a GUI password and you'll get this error if that's the case, but want to see what the issue is for others.

possibly related to #356

**Comment by patdelaney** [comment] 2018-03-12 17:42
I enclosed the nginx log  this is a 2.x system 

 

Pat

**Comment by jaredb7** [comment] 2018-03-13 13:17
Hi Pat, log didn't come through. But found the cause for multisync timeout.
I've posted a fix for the issue in 2.x, will also add the fix into 1.x also.

**Comment by cpinkham** [comment] 2020-01-16 05:25
Believe this is fixed in latest FPP v3.5.x

**Closed by cpinkham** 2020-01-16 05:25 UTC
