### ISSUE TITLE
Turn on DNS support

### ISSUE THREAD

**Issue by cybercop23** [FalconChristmas/fpp#1068] opened 2021-08-09 04:19 UTC
**Is your feature request related to a problem? Please describe.**
When helping users in the Zoom room to set up a Falcon connected to a PI.. the network and proxy settings are sometimes challenging and time consuming for them to follow.

**Describe the solution you'd like**
Since dnsmasq is available, add an option to turn it on and serve IPs to eth0.
When a user has a Falcon connected to a PI via eth0 or even a switch, when this option is on and a range is selected, anything connected to the PI's eth0 will be leased an IP.
Additionally, to make this full feature, add any and all served IPs to the proxy list.

**Describe alternatives you've considered**
Always have to manually set up network and proxy configs.

**Additional context**
This is mostly required for non FPP based controllers. No need for me as I only use Kulps.

I tested this with a Pi3 as master and Pi4 as remote connected to the Pi3 with a cat5.
Turned on dns on Pi3...
dnsmasq -i eth0 -F 192.168.100.100,192.168.100.110,255.255.255.0,12h 
or...
interface=eth0
expand-hosts
dhcp-range=192.168.100.100,192.168.100.110,255.255.255.0,12h

manually added the proxy.. but should be easy to append each leased address to /home/fpp/media/config/proxies

I was able to move between the two as expected.
Configured xLights to use the "master/pi3" as the proxy and used the leased IP as the controller IP and all is working as expected.

I think this will go a long way to ease the initial setup for new users and help speed some of the issues/questions people get in the Zoom room.

**Comment by darylc** [comment] 2021-08-10 03:17
Can you help me understand why this is useful?  Enabling DNS resolution for devices behind the eth0 then just gets them to the next bottleneck where they can't actually access the Internet? Something like this https://github.com/FalconChristmas/fpp/issues/1067 seems much more useful?

**Comment by cybercop23** [comment] 2021-08-10 03:52
The above will reduce the manual work the Zoom room spends with new users trying to set up Falcons controlled by FPPs. The majority of them do not need to reach the internet from the Falcon. They are just setting up controllers on a "show" netwrok behind a Pi.
If #1067 will have the ability to turn on DNS and serve IP addresses to the show network and add them to the proxy so xLights can get to those controllers, then it will achive the same outcome.
The way I see it, one (this one) is a must have requirement/setup in order to get to the conntoller, and #1067 is additional to expand on the capabilites.

**Comment by darylc** [comment] 2021-08-10 04:17
@cybercop23 Oh you want to turn on DHCP support, not DNS.

Can you please update the issue to reflect that?

**Comment by darylc** [comment] 2021-08-10 04:32
This is a duplicate of https://github.com/FalconChristmas/fpp/issues/118 

Please close

**Comment by ghormann** [comment] 2021-08-13 23:15
Closing as duplicate of #118

**Closed by ghormann** 2021-08-13 23:15 UTC
Labels: enhancement
