### ISSUE TITLE
Unable to use "Next or Previous" when playing sequence in "Lead in/out" section of playlist.

### ISSUE THREAD

**Issue by horathgar2000** [FalconChristmas/fpp#715] opened 2020-04-29 18:14 UTC
Hey awesome programmers, I have just noticed that I am unable to change the playing sequence if it is in the "Lead in or Lead out" section of a play list. It works fine if it is in the "Main Playlist" section but my assumption is that we should be able to change it.

I can select any of the sequences and click play and it will play the sequences that are in the Lead in/out.

Version Info |  
-- | --
FPP Version: | v4.x-master-287-g915b92f5
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v4.0-alpha
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 00000000536ce80e
Kernel Version: | 4.19.97-v7+
Local Git Version: | 915b92f ChangeLog
Remote Git Version: | 915b92f

**Comment by cpinkham** [comment] 2020-04-29 23:30
This was by design originally, the code specifically checks that we are in the Main Playlist section.  I do think it can be updated though, so marking this as an enhancement for v4.0.

**Closed** 2021-01-12 05:51 UTC
Labels: enhancement
