### ISSUE TITLE
Volume Issues

### ISSUE THREAD

**Issue by Materdaddy** [FalconChristmas/fpp#96] opened 2014-06-08 23:21 UTC
Currently the volume control only works on "PCM" which isn't necessarily the name of the audio device when we custom-configure something using the /root/.asoundrc file.  With the VastFMT as the audio source, the audio isn't changeable via the UI currently.

**Comment by ihbar** [comment] 2019-03-30 16:34
Hello
This seems to be a very old ticket, and from the last comment of 2014, it is not a bug anymore. I think we should close it. (Just to clean the list)
Any opinion ?
Stephane

**Closed** 2019-03-30 16:38 UTC
Labels: bug
