### ISSUE TITLE
Color Order when Bridge Mode through FPP from Xlights

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#594] opened 2019-11-18 04:45 UTC
I've went through and set up the Falcon controllers now 3x. I set them to xLights where xLights was outputting directly to the Falcons for testing. I ensured I had E1.31 Unicast 512 universe size set up on both sides. and the color order set.

I then went into FPP, set the outputs again, and now all the color orders are off when running testing mode. 

I reset the Falcon controllers to obey the FPP color outputs. 

Then I put FPP in Bridge mode, set the inputs, and set XLights output to the FPP bridge, and all the colors are off again. 

Why is R not R, and G not G, and B not B for all the exact channel configurations. This year has been so difficult in setting things up. I even did discovery and  let the Xlights send it to FPP using DDP. 
Same thing, colors are all off. Now i'm VERY confused what I need to set what to what based on  an FSEQ from Xlights how it will play on FPP!
THis is using v3.5.2

**Comment by dkulp** [comment] 2019-11-20 16:06
This needs to be a question on the Falcon forums, not a bug/issue report.    In anycase, the testing page has absolutely no knowledge of the outputs, how strings are assigned to channels, etc...  When enabled, it's always just "first channel is R, second is G, third is B, etc..."   If channels in props don't line up with that, the colors displayed on the pixels will likely not match.   I've added a warning to the page to mention that.

**Closed by dkulp** 2019-11-20 16:06 UTC
