### ISSUE TITLE
Can a time check be added to system health check?

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1834] opened 2024-04-27 00:56 UTC
Seems things break with github pulls etc if the date is way out of whack. Is that something that could be flagged in the system health check? (realize that if it is broken you dont know what the real time is ..hmmmm)
ping hits github.com but there are cert errors if the date is too old.

**Comment by patdelaney** [comment] 2024-05-15 21:12
psudo code:
Check for existence of Clock chip
 If yes get time and store value, note the tmezone, set variable true
 if no then no clock, move on
 Check for internet ntp and or local ntp server
  if yes get time and compare  Print Result message
     if clock way off alert user to check time
 if no, then print "time unknown"
 
Just a thought?

**Comment by cybercop23** [comment] 2024-05-15 21:19
That's tehre in 8.
![image](https://github.com/FalconChristmas/fpp/assets/23619433/db7c25aa-267b-4f1f-bb95-824bd754ab51)

**Comment by darylc** [comment] 2024-06-18 11:52
@OnlineDynamic Any interest in this one?

**Comment by OnlineDynamic** [comment] 2024-06-18 15:43
@derwin12 looks like the health check functionality is already there but perhaps you can give a screenshot of the error scenario invloving github and we can look to make that more user friendly if not obvious what the issue is

**Comment by derwin12** [comment] 2024-06-18 17:33
It was from a user in zoom. Their fpp date was years out of date .. perhaps some default. When it went to hit github it would give a cert error since the date was so long ago. Not sure what the Time offset check is - perhaps that does the date check?? (is that somewhat new?)

**Comment by derwin12** [comment] 2024-06-18 17:39
So in fpp set the date to something long ago..

date -s '2014-12-25 12:34:56'
Now do a health check. Can this be flagged as not a reasonable date or
something?



[image: image.png]

Results in a github pull failing
[image: image.png]

Thu 25 Dec 2014 12:36:51 PM EST
Can not access https://github.com/, unable to pull git updates

**Comment by OnlineDynamic** [comment] 2024-06-18 18:42
How about I add logic to compare system date with the client browser date and flag if different? That way there is something to compare against if the fpp instance isn't connected to the Internet for a time source

**Comment by cybercop23** [comment] 2024-06-18 19:45
If the Date/Time are off, won't they be caught ny the Time Offset check?
`ntpq -nc peers`
If not, then what's the pourpose of this check?

**Comment by OnlineDynamic** [comment] 2024-06-18 19:49
> If the Date/Time are off, won't they be caught ny the Time Offset check? `ntpq -nc peers` If not, then what's the pourpose of this check?

They would only be caught if the network time protocol is able to retrieve the time from a network source/time server - this won't be the case if not connected to the internet or a local time server

**Comment by OnlineDynamic** [comment] 2024-06-19 20:17
Fix for this now live on the master branch health check page - the old TimeOffset check has been renamed to make it clear it relates to NTP and a new helthcheck add which compares the fpp system time against the browser and if more than 10mins apart shows an amber warning and if more than 10 hours apart a red warning

**Closed** 2024-06-22 23:24 UTC
Labels: enhancement
