### ISSUE TITLE
Running FPP 5.x through proxy (fpp through fpp proxy) shows no header / menu bar

### ISSUE THREAD

**Issue by LightsOnHudson** [FalconChristmas/fpp#1147] opened 2021-11-09 14:05 UTC
Running the FPP through a proxy like the falcon controllers. does not show the menu drop downs.
see attachment.
<img width="1430" alt="Screen Shot 2021-11-09 at 7 04 08 AM" src="https://user-images.githubusercontent.com/10136122/140938412-ea812e9e-ed11-4134-9f69-55bec961e3ec.png">

**Comment by dkulp** [comment] 2021-11-09 21:39
I'm not able to reproduce this when using FPP 5.3.1 through an FPP 5.3.1 proxy host.   Menus appear and work fine.

**Comment by bcarriveau** [comment] 2021-11-09 21:42
We see this from time to time, it's usually some dumb 3rd party firewall , antivirus type deal or even an odd browser.

**Comment by cfmorrell** [comment] 2022-09-11 02:30
I'm seeing the same thing in FPP 6.0.2-9-gf245c06d.  When I access my F48 through the FPP proxy, no issues.  When I access my F16v2 through the proxy, I'm unable to see any string ports or E131 configuration:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/6538191/189509369-77df8c05-7562-47e7-8baf-d8b56d3a0ef1.png">

When connecting directly to the F16v2 (same browser - Chrome, same computer - Macbook Pro, same browser plugins enabled, just an SSH proxy through FPP), all works well: 

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/6538191/189509390-d47ac606-0774-4113-aab7-fed945268ed2.png">

Looks like it could be some kind of old code in the F16v2 that isn't getting passed through the proxy correctly.

**Comment by darylc** [comment] 2023-01-01 12:05
The F16v2 doesn't work properly through a proxy - would need to be fixed in firmware on their side.  The other issue raised originally in this issue can't be replicated.

**Closed by darylc** 2023-01-01 12:05 UTC
