### ISSUE TITLE
F8-PB - Two songs are stopping FPP every time.   

### ISSUE THREAD

**Issue by jefft0825** [FalconChristmas/fpp#604] opened 2019-11-28 02:17 UTC
2 songs are making my remote F8-PB stop running at 20 seconds in at the same exact spot every time.   I restart FPP and it starts right back up.    I have tried v2 and v2 sparse - same issue occurs.    I have tried different versions of xlights as well.     Last one i tried was .64

**Comment by jefft0825** [comment] 2019-11-28 02:25
Does this with xscheduler as well running f8-pb in remote

**Comment by cpinkham** [comment] 2020-02-05 22:58
Removing links since they contain both a .xml for a sequence that is for sale and the .mp3 from Amazon.

Can you confirm that this is still an issue with the latest FPP v3.6.x and xLights 2020.x?  If it is reproducable, please also try it putting the F8-PB in master mode and playing the sequence to see if it also exhibits the same problem.  If so, I have saved off the zip files and can try to reproduce the issue here by regenerating the .fseq using the xml you provided.

**Comment by darylc** [comment] 2021-06-20 05:46
lets close this given the lack of input from the OP

**Closed** 2021-06-20 12:11 UTC
