### ISSUE TITLE
"Failed to save Latitude" error when pasting lots of digits

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1349] opened 2022-08-31 21:50 UTC
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
FPP 6.0.2 on K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce.
- Boot and perform initial setup.
- Paste latitude `33.880745601014254`.
- Paste longitude `-118.388834358193`
- Get error "Failed to save latitude".
- If ignoring error and click "finish setup"
  - Get an API error message, then page goes 404.
  - FPP is no longer responsive, must power cycle.
  - After power cycle no more FPP WiFi.
  - Must rewrite SD card and restart setup process.

**Expected behavior**: 
Expect no error, even if truncating location accuracy during paste.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by ghormann** [comment] 2022-09-18 00:08
@ptr727  What browser was this?   I jsut tested with Current and Chrome and I'm unable to reproduce.    In fact the UI prevents entering in that many characters in my testing.

**Comment by ptr727** [comment] 2022-09-18 18:48
Google Chrome in Win11, paste the values.

**Comment by mjunek** [comment] 2022-09-24 05:13
I had a similar issue with Firefox on Windows 10 - pasting (not typing) into the field. If you use the 'Google Maps' accuracy Lat/Long after clicking your property - such as 
Latitiude: -33.8506675
Longitude: 151.210931

In my case, I just pulled a few numbers off the right to reduce the values to 6 significant figures (Rather than 9) and it worked. I did not test with other lengths.

**Comment by dkulp** [comment] 2022-09-26 20:01
I haven't been able to reproduce this at all.  However, I just increased the fields to 15 characters which will hopefully allow the full length to be pasted in.

**Comment by mjunek** [comment] 2022-09-30 05:12
Hi Dan, 

I was able to replicate the fault on my end, and it's unrelated to the length. The problem occurs when using the initial setup page, and you change the hostname of the device. By the time you get down to the bottom of the page where the latitude and longitude boxes are, the MDNS cache for fpp.local has expired, and is no longer resolving. Therefore the XMLHttpRequest fails as the DNS lookup does not succeed.
Accessing the device again using the new hostname, (or via IP address) allows the entry to then work.

So - I think maybe there needs to be one of the following:
1. A warning if the hostname is changed to start using the new one, if the HOST: header is equal to the old hostname rather than IP address
2. Force a page refresh for the new hostname once it is changed - however MDNS may not be 100% ready at this point
3. Force a reboot after the hostname has been changed - without allowing any additional setup parameters
4. Not allow the hostname to be changed on the initial screen. 

With point 4 in mind though, I was able to replicate a second time on the later configuration, due to exactly the same reason.

**Comment by ptr727** [comment] 2022-09-30 19:13
That's interesting, I do always change the hostname as part of initial setup, wonder if that could also be related to https://github.com/FalconChristmas/fpp/issues/1350

**Comment by cpinkham** [comment] 2023-01-04 21:28
Option 5: Update the HostName setting config in settings.json to have its own custom onChange function which could be a combination of options 1 & 2.  The function would save the setting, then check to see if the user is connected via the old hostname and if so fire a timer.  When the timer triggered, a check function would be called to check to see if the new hostname was responding yet and if the old one quit responding.  If so, then a popup could direct the user to reconnect to the new hostname.  If the new hostname wasn't responding, reset the timer to check again in X ms.

I don't think we want option 3 or 4.  The 3 reboot can wait until after the other initial settings are set and 4 would kind of defeat the purpose of having the initial setup page.

**Comment by mjunek** [comment] 2023-01-04 21:53
Are there any client side DNS caching that could cause problems with detecting the host name change from the server side?
Could the name change not be done using an async call from the browser on tab, but in the "Finish Set up" button, which brings up the "browse to xxxx" page once it's detected to be changed?
If it's done asynchronouy, and users browse through half way through set-up, how many changes will they need to redo?

**Comment by cpinkham** [comment] 2023-01-04 22:24
Perhaps an option 6 is best.  If we disable the avahi daemon restart when the HostName setting is saved, the MDNS hostname wouldn't change until after the reboot.

**Comment by mjunek** [comment] 2023-01-11 06:22
Option 6 certainly sounds like the best way forward, and trigger the reboot flag to bring up the banner.

**Comment by darylc** [comment] 2023-01-11 11:47
Note that this problem is not limited to the initialSetup page, it also applies to changing the hostname generally in FPP.  I'm testing a fix.

**Comment by darylc** [comment] 2023-01-12 08:40
So this is interesting, I went to replicate this fault with a brand new 6.3 image on a PI because I wanted to test that the fix actually worked.

Using Windows 10 and firefox/chrome, I can't actually get the initial setup page to fail, even when changing the hostname and filling it in slowly, my browser(or OS) does not expire the old hostname out before I press finish setup. 

This impacts the fix, because I noticed in my testing for the potential fix, that even if I disable the avahi daemon restart (Option 6), avahi notices the new hostname anyway my browser can access FPP via both old and new hostnames.  This means that clients with the timeout issue would probably have it in Option 6 still even if removed the avahi restart.

Perhaps we need an option 7 - fpp applies the hostname change after the reboot?

**Comment by dkulp** [comment] 2023-01-12 19:24
Another option (which we also need on the multisync page) is to immediately redirect to the IP address for the initial setup (and multisync) page.    Basically, detect if the browser is using the host name and redirect to the ip so the browser just uses the IP.   

This is needed for the multisync page due to COORS.  If you go to the multisync page via hostname and then try to have it run something on all the remotes (like do an FPP upgrade), they all fail as COORS will block it.   Going to the multisync page via IP address works.

**Comment by ptr727** [comment] 2023-01-12 22:15
> Another option (which we also need on the multisync page) is to immediately redirect to the IP address for the initial setup (and multisync) page. Basically, detect if the browser is using the host name and redirect to the ip so the browser just uses the IP.

IP's are non-deterministic when using DHCP, and I a human, at least me, don't know which IP points to which device when I have many, while hostnames in the URI bar are easy to identify. I'd then rather vote for mechanisms that make network stack changes on reboot, as used by many other devices. This also allows DHCP to register the device id correctly in DNS on the next lease request.

**Comment by mjunek** [comment] 2023-01-12 22:58
> IP's are non-deterministic when using DHCP, and I a human, at least me, don't know which IP points to which device when I have many, while hostnames in the URI bar are easy to identify. I'd then rather vote for mechanisms that make network stack changes on reboot, as used by many other devices. This also allows DHCP to register the device id correctly in DNS on the next lease request.

Whilst that gets around the first issue which is essentially what was discussed above, it doesn't fix the CORS issue that @dkulp is referring to, which needs an IP address to operate, or all the remotes to share a common allowed domain (which won't happen easily). 

I think all suggestions above are good - 
Option 6, don't do anything until reboot, redirecting to IP in the interim, and redirect to IP on Multisync page.

The redirects to IP will need reauthentication though, should the front-end password be enabled as it's a different host.

**Comment by darylc** [comment] 2023-01-29 03:17
The FPP Development team discussed this and decided to implement the hostname change after reboot.  CORS issues for the multisync page are out of scope for this particular ticket.

**Closed** 2023-01-29 03:23 UTC
