### ISSUE TITLE
Rpi 3 b+ Persistent Name Problem

### ISSUE THREAD

**Issue by Francesco-Rugg** [FalconChristmas/fpp#1437] opened 2022-12-12 23:19 UTC
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
FPP version 6.2 running on Raspberry pi 3 B+

**Describe the bug and Steps to reproduce**: 
There's a problem using default ethernet (eth0) and an ethernet usb adapter (eth1).
I use this adapter to drive a Color-Light Card for my LED Panels.
**With version 5.5 I don't have this problem**.
When I setup the eth0 to static ip and leave eth1 in dhcp (like in my network setup in fpp version 5.5)and after follow the steps for persistents names in the manual the Pi starts, I can see my ethernet light but I can't acces to the PI.
If I unplug the ethernet usb adapter the PI works as expected with eth0

**Additional context**: 
Without create persistent name the PI starts but with a different IP and not the one that I insert in the network page

**THIS IS THE LOG FILE**
[FPP_Logs_20221212.2304.zip](https://github.com/FalconChristmas/fpp/files/10212710/FPP_Logs_20221212.2304.zip)

**Comment by darylc** [comment] 2023-01-08 03:42
duplicate of #1335

**Closed by darylc** 2023-01-08 03:42 UTC
