### ISSUE TITLE
The ability to configure wlan0 when no wireless adapter is detected

### ISSUE THREAD

**Issue by MDickson00** [FalconChristmas/fpp#1334] opened 2022-08-09 19:16 UTC
Can a feature be added that will allow the setup of a wlan0 when no wifi adapter is currently present?

Helping setup a pocket beagle in zoom, wifi tethering is not working so we are using USB tethering, since the cape is not currently powered, the wlan0 isn't available to configure. I realize this would only be helpful for a small number of users, but may be helpful in other circumstances as well.

**Comment by cpinkham** [comment] 2022-08-12 21:44
Closing as duplicate of #1241

**Closed by cpinkham** 2022-08-12 21:44 UTC
Labels: enhancement
