### ISSUE TITLE
K4-PB button debounce issue multiple presses

### ISSUE THREAD

**Issue by ptr727** [FalconChristmas/fpp#1411] opened 2022-11-12 03:27 UTC
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
FPP 6.2, K4-PB

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Press Test or Enter buttons on K4-PB
2. If quick pressing the button will click twice.
3. To not double click I have to click hold release

**Expected behavior**: 
Expect single logical click with single physical click.

**Additional context**: 
Suspect debounce timing issue.

**Additional Attachments**
NA

NA

**Comment by darylc** [comment] 2023-01-01 11:45
duplicate of #619

**Closed by darylc** 2023-01-01 11:45 UTC
