### ISSUE TITLE
Special characters are problematic and causing issues for users this season

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1181] opened 2021-12-01 20:11 UTC
What worked last year is not working this year. It's Beginning .. the single apostrophe in music and/or sequences is stopping fpp .. causing lots of people to come to the zoom room. This worked in 4.x versions of fpp.
Hoping there is a fix in the upcoming releases..

**Comment by cpinkham** [comment] 2021-12-02 01:04
I'm unable to reproduce this.  I have a test sequence file called "Sync Test'.fseq" and corresponding mp3 called "Sync Test'.mp3" (note, both a space and a single quote in each filename).  I used the FPP UI to create a playlist containing the fseq and mp3 and was able to play it  successfully manually via the status page as well as via a schedule.

Are these playlists being created by the users manually or uploaded from xLights?

Is fppd stopping or is the sequence/media stopping or is the playlist stopping?  We really need more info to troubleshoot this issue at all.  If the playlist file is uploaded via xLights, we'll have to see what is in it.  You can access the playlist directory via the network share in the \\YOURFPPIP\FPP\playlists\ directory.  You should see a .json file for each playlist which you can then copy off and attach to the ticket.

**Comment by ghormann** [comment] 2021-12-02 02:36
@derwin12 I've never seen this result in an fppd crash.  Can you provide a repeatable test case for that? 

Is it correct that the people having issues are all using xlights with **FPP Connect** to upload the sequences?  I thought I corrected that prior to 5.4 (perhaps even in 5.3).      Here is a video of me testing this with apostrophes.   The special characters are stripped during fpp connect and the playlist is still correctly created.   Thus, I'm not seeing a problem.

https://www.youtube.com/watch?v=2jX7H3CWO8M

Thanks in advance for clarifying.

**Comment by bcarriveau** [comment] 2021-12-02 02:56
Can confirm several times a week in zoom we have issues to special characters causing fpp to stop or playlists/schedules not to function.  Most common are ( ' ! & |  ) . Having an empty playlist will park FppD on its bottom aswell we have noticed.

**Comment by derwin12** [comment] 2021-12-02 03:58
Common one is You're a mean one Mr. Grinch.fseq
That is a slanted quote and a period.
Also
Panic! At the disco - into the unknown.fseq

**Comment by emil-johansen** [comment] 2021-12-02 07:53
Here in Denmark, a lot of people have had problems with uploading outputs to FPP when using characters æ ø å in model names.

Xlights try to send the model names to FPP, and FPP disables the Cape output completely.

**Comment by derwin12** [comment] 2021-12-02 14:02
Try this character in your testing   You´re     (that is alt + 0180) not the ' character on your US keyboard

**Comment by Jchuchla** [comment] 2021-12-06 05:23
I haven't had issues with FPPD crashing.  I've got lots of sequences with spaces, and 2 with apostrophes.  But I have had issues with remote falcon.  The RF queue will get stuck when there's an apostrophe in it.  The regularly scheduled playlist continues as usual though. 
I can also say that I have never uploaded to my FPP via xLights or FPP Connect.  Everything was transferred to the pi via samba share.  Schedule created manually on the FPP itself.  Actually the schedule and playlists were brought forward from previous versions and tweaked as I went along.
Just a few data points in case it helps.

**Comment by whitesoup12** [comment] 2022-04-12 12:37
> I haven't had issues with FPPD crashing. I've got lots of sequences with spaces, and 2 with apostrophes. But I have had issues with remote falcon. The RF queue will get stuck when there's an apostrophe in it. The regularly scheduled playlist continues as usual though. I can also say that I have never uploaded to my FPP via xLights or FPP Connect. Everything was transferred to the pi via samba share. Schedule created manually on the FPP itself. Actually the schedule and playlists were brought forward from previous versions and tweaked as I went along. Just a few data points in case it helps.

I know this one has been sitting a while, but wanted to follow up on the issue with RF and special characters. While it's still recommended to omit special characters from file names, the latest version of RF API that was written in Java has been tested fully with special characters and has no issues.

**Comment by cpinkham** [comment] 2022-06-17 02:03
Adding this to v6 so we can discuss or take a look at it.  I don't know if any related fixes have gone into v6 for this yet or there was other work, but it does need attention or a solution before things heat up later this year.

**Comment by darylc** [comment] 2023-01-28 05:07
The FPP development team met and discussed this issue.  They are happy to fix problems with filenames, but need precise examples, eg 'when I try to upload foo@$%@$';,...mp3 via fpp connect, the file is not visible in the fpp file manager after the upload`

**Comment by derwin12** [comment] 2023-01-28 18:16
Examples were given in prior comments
Panic! at the Disco - In to the Unknown.fseq for example (the !). 
Elmo & Patsy - Grandma.fseq .. (the &)
The extra period in names like blah blah (ft. Lauren Daigle).fseq
Not certain on the () if they are a problem or not - but often suggest to remove them.

**Comment by darylc** [comment] 2023-01-28 22:35
@derwin12 Yes, but doing what with those files?

**Comment by derwin12** [comment] 2023-01-28 22:46
fpp connect .. then fpp cant find them since it strips out the characters
then the sequence doesnt match the audio.
I think in v4 versus v5 & 6 - the audio is determined based on what is
encoded in the fseq. With the names being stripped on upload, they no
longer match the fseq contents.
The user has to go back to xlights - rename the audio and the sequence and
reupload.

Make up some fseq file - put those "funny" characters in the name - use fpp
connect and then look at the name in fpp. It is changed.

**Comment by derwin12** [comment] 2023-01-28 23:31
Here is a simple example ..
Here is the file in the upload.. with this nice looking file name .. lol.

![image](https://user-images.githubusercontent.com/4643499/215295837-d1422dc1-752a-4a60-983d-8bef3407aaec.png)

FPP shows this file in the file manager...
![image](https://user-images.githubusercontent.com/4643499/215295821-71aa28fb-477f-4965-8ef9-7b30ff945967.png)

**Comment by darylc** [comment] 2023-01-29 02:01
Talked to derwin12 on zoom.  Sanitisation of file names is OK and doesn't break things.

Some specific file names still cause problems.  Eg You´re.mp3 You´re.fseq both can be uploaded via the file manager and FPP sanitises them OK, but when you upload them via FPP connect, no errors are raised but the files also don't end up on FPP.  Both the file manager & fpp connect upload via jqupload.php so perhaps something is going on at the xlights side?

**Comment by darylc** [comment] 2023-02-07 10:59
The commit above fixed files with special filenames showing unknown as their length in the filemanager

**Comment by darylc** [comment] 2023-03-18 09:33
Closing this out since Dan has re-written a bunch of stuff that changes the handling of uploaded files.  If there are new bugs in 7.x master or beyond we need new examples.

**Closed by darylc** 2023-03-18 09:33 UTC
