### ISSUE TITLE
SSID was truncated 

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#865] opened 2020-11-12 21:03 UTC
Issue on zoom using 4.3 so perhaps fixed in a later version?

Anyways .. his ssid was "Ralph is taking over. Come Now"
the drop down only showed "Ralph".
We didnt confirm and assumed it was "Ralph" turns out it was that entire string.

So perhaps the drop down truncates after the first space?

Again this was in 4.3 so if fixed, please close.

**Comment by dkulp** [comment] 2020-11-12 21:10
Duplicate of #855 and fixed in 4.4

**Closed by dkulp** 2020-11-12 21:10 UTC
