### ISSUE TITLE
3.5.3 - Stopping Effects just "pauses" them still

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#601] opened 2019-11-25 23:42 UTC
I formatted my card, added 3.5.3 and a few effects, if I start an effect and then hit stop the lights on that particular effect still stay on and the motion of the effect just pauses. It used to shut off properly a few builds ago.

If I have a 10 second effect and hit play and leave it it will stop properly and shut off but I loop effects and then stop mid show and they pause

**Comment by bchiaino** [comment] 2019-11-25 23:43
I formatted my card, added 3.5.3 and a few effects, if I start an effect and then hit stop the lights on that particular effect still stay on and the motion of the effect just pauses. It used to shut off properly a few builds ago. 

If I have a 10 second effect and hit play and leave it it will stop properly and shut off but I loop effects and then stop mid show and they pause

**Comment by chrkov** [comment] 2019-11-28 03:30
I am seeing this same issue.   To add to it, if you stop the effect a second time, then it will completely turn off.

**Comment by nmiller0113** [comment] 2019-12-03 09:12
I'm seeing this in 3.5.5 as well.  Just experienced it tonight.  Running in standalone mode, but triggering this via an FPP Command for Remote Effect Stop from my Master controller.  This is a P5 Panel used for tune to and not synchronized to anything other than the Master schedule telling it when to stop and start.  @bchiaino, have you heard anything back from @dkulp on this?  The only fix I have now is running the FPP Command for Remote Effect Stop twice, back to back, from the Master for it to fully shut off.

**Comment by dkulp** [comment] 2019-12-05 19:32
Someone needs to provide some way to actually reproduce this.   If I start an effect on a virtual matrix on my pi connected to a monitor, it starts.  When I click stop, it stops and the screen goes black.

**Comment by bchiaino** [comment] 2019-12-05 19:38
hmmm, I don't know if you can check it on mine but I can reproduce it every time. I have a model exported as a ESEQ and in FPP I simply start it and then try and stop and it pauses every time. this is with pixels connected to a f48 receiver board

**Comment by nmiller0113** [comment] 2019-12-05 20:30
@dkulp, I can reproduce it as well.  Mine was even different than @bchiaino.  In my setup I was using FPP Commands from my Master to run "Remote Effect Stop" of an FSEQ, not ESEQ, effect that was kicked off via "Remote FSEQ Effect Start" of a FPP Standalone instance, not FPP Remote, that is my tune to sign and not synchronized with the show at all.  To add some additional info, that may or may not be helpful, It used to actually be a FPP Remote in Multisync, but that was because I had some dumb assumption it needed to be for FPP Remote commands to work.  Then one day I started experimenting to test that theory...primarily because when setting up a playlist I noticed that the dropdown for the FPP Remote Command recognized all of my FPP instances, not just the ones setup as FPP Remote Multisync instances.  Turns out it doesn't need to be setup as an FPP Remote Multisync instance to allow the Master, or even non Master, playlist FPP Remote Commands to be triggered on a Remote FPP instance. Sorry that was long winded...my reason for saying this that as an FPP Remote Multisync instance the effects would stop AND shut off completely.  Once I changed to FPP Standalone for this instance it started showing this freeze and no shut off behavior.  I hope that was helpful and not even more confusing :)

**Comment by chrkov** [comment] 2019-12-05 22:38
I can reproduce it every time as well.  Open to giving you access to it if needed.

**Comment by dkulp** [comment] 2019-12-06 14:20
I believe this is now fixed on master... if anyone could verify, that would be great.

**Comment by chrkov** [comment] 2019-12-06 19:28
I just upgraded to 3.5.6 and tested.   Mine now is working correctly.

**Comment by dkulp** [comment] 2019-12-06 19:30
Awesome.  Thanks!

**Comment by bchiaino** [comment] 2019-12-06 19:31
nice! thanks Dan!

**Closed by dkulp** 2019-12-06 19:30 UTC

**Comment by nmiller0113** [comment] 2019-12-06 19:35
I tested successfully as well!  Thanks @dkulp!  By the way...watched Beep Beep, I'm a sheep...haha nice!
