### ISSUE TITLE
FPP routing issue

### ISSUE THREAD

**Issue by marciuliani** [FalconChristmas/fpp#484] opened 2018-12-20 03:47 UTC
I have an issue running a Raspberry Pi 3 B+ version 2.5.3 on my Master.  I have a typical network with a static ip and default gateway setup on my WLAN0 and a private connection from the eth0 of my master to a dumb hub with no gateway which connects to my show network.  My wireless management (home) network is 192.168.254.0/24.  My Pi is 254.225 with a default gw of 254.1 (my asus router).  My Eth0 of my master is 192.168.253.1/24 with no default gateway.  I am forwarding port 80 on the pi to port 8887 on my router so I could access it remotely.  If I reboot the master everything works fine, but what I find is that after a period of time - the route gets stale and injects everything back into the eth0 network.  Pinging www.google.com resolves and ip but does not get a response when both wlan0 and eth0 are enabled.  If I disable eth0 and reping google - I get a response.  When I re-enabled eth0 there is no longer a response.  Once I reboot the Master - it works again for a period of time then stops working.  I could duplicate the issue if needed - I presented the issue on tonight's zoom and Alex recommended that I open a bug report with what i've explained above.

Thank you,
Marc

**Comment by cpinkham** [comment] 2020-01-16 06:13
This sounds like it might be DHCP updating the interface, are you using a static IP on eth0 or DHCP?  Please try to reproduce on the latest FPP v3.5.x to see if this is still an issue, otherwise we will probably close the ticket as fixed in the newer OS and FPP version.

**Comment by cpinkham** [comment] 2020-12-02 05:08
Closing ticket as this version is so old and we have been through an OS upgrade since then.

**Closed by cpinkham** 2020-12-02 05:08 UTC
