### ISSUE TITLE
SSH Shell not running effects

### ISSUE THREAD

**Issue by roccojay12** [FalconChristmas/fpp#990] opened 2021-04-28 12:17 UTC
When running :

fpp -e "effectname"

The effect starts and shows that it is running on the effect status page but the effect doesn't actually run on the lights,

hardware : 

Raspberry Pi 3 
FPP Pi Hat 
WS2811 String Pixels

Logs:
[FPP_Logs_20210428.zip](https://github.com/FalconChristmas/fpp/files/6391710/FPP_Logs_20210428.zip)

**Comment by ghormann** [comment] 2021-05-30 21:50
@roccojay12  Looks like you are reporting this on v4.6.1.    I'm unable to reproduce this problem in the current version of master and don't have a 4.6.1 box for testing.
- Given that it displays on the UI, have you confirmed your model is mapped to the correct channels? Seems like a possible source of the problem.
- I can confirm this works fine on master (development branch for 5.0) -  https://www.youtube.com/watch?v=kxh805mZ1-0

**Comment by ghormann** [comment] 2021-06-19 23:43
Closing as unable to reproduce in 5.0-alpha.   No reply to request for more info.

**Closed by ghormann** 2021-06-19 23:43 UTC
Labels: Need Info
