### ISSUE TITLE
FPP 4.0: Issue with DNS resolution when using DHCP

### ISSUE THREAD

**Issue by swampdogmash** [FalconChristmas/fpp#747] opened 2020-06-18 04:42 UTC
DNS via DHCP doesn't seem to function. Once booted, trying to resolv and internet FQDN for a host or a local zone name results in pinging a host.

ping: example.host.domain: temporary failure in name resolution

Not sure if this is just me misunderstanding...

The dhclient leases file shows the correct dns settings are being picked up but resolv.conf shows the nameserver set as 127.0.0.1 (my limited knowledge of the buster config now kicks in and this might be correct). Am I doing something wrong?

This seems to be the case for the fpp user and for root under sudo.

running "sudo dhclient"  seems to fix it though.......

**Comment by skydiveguy** [comment] 2020-07-02 23:21
I have this issue as well on a clean install of v4.0.
Your solution resolved my problem as well. Thank you.

**Comment by ghormann** [comment] 2020-10-06 23:55
I'm unable to reproduce on 4.1 or 4.2 both configured with DHCP.   I'm going to close this.  Comment to reopen if still an issue. 
![image](https://user-images.githubusercontent.com/24968726/95272226-d836d000-080d-11eb-8bcb-9eb7fbc43b5a.png)

**Closed by ghormann** 2020-10-06 23:55 UTC
