### ISSUE TITLE
Linsn RV908

### ISSUE THREAD

**Issue by ScobbyDoo** [FalconChristmas/fpp#1354] opened 2022-09-03 16:12 UTC
I've tried to configure linsn this card with 4 different release version of FPP but no luck.

Got perfect video output from pc (screen overlay top left corner)after configured RCG file.

On test pattern from FPP or send data through Xlights, show last frame ( configured time- top left screen ).

Mac is same as configured system, later on i read all forums searched keywords (linsn) but i realised that not even single working video or picture or tutorial available on forum. 

Any hint ?
Thanks.

**Comment by darylc** [comment] 2022-09-03 23:34
Duplicate of https://github.com/FalconChristmas/fpp/issues/769 

I've also tried to get linsn cards working in FPP, I believe it's been broken for many years.  A good workaround is to use a sender card with a virtual matrix, or a colorlight card.

**Closed by darylc** 2022-09-03 23:34 UTC

**Comment by ScobbyDoo** [comment] 2022-09-03 23:37
Yes that is only option right now, but latest release of FPP have this option for output that's why i tried

Anyway thanks for pointing out that
