### ISSUE TITLE
Scheduler error causes issue with FPPD

### ISSUE THREAD

**Issue by tielur** [FalconChristmas/fpp#911] opened 2020-12-07 06:22 UTC
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*
FPP 4.5 running on Raspberry Pi 3

**Describe the bug and Steps to reproduce**: 
1. I was editing my schedule by dragging and dropping one playlist above another
2. I noticed FPPD was stopped and it wont start even after a reboot now

**Expected behavior**: 
FPPD would be started

**Additional context**: 

**Additional Attachments**
`/var/log/syslog`
```log
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:08:00.630 (11636) Scheduler.cpp:845: ---- ----------------------- ------------ ------------------- ---------------------------------------------
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:08:00.631 (11636) Scheduler.cpp:863: +  G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Christmas 2020
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:08:00.631 (11636) Scheduler.cpp:863: + *G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Static
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:08.000 (11636) Scheduler.cpp:722: Schedule Entry: 17:19:07 - 23:00:00 - Stopping Playlist Gracefully
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:31.848 (11636) Scheduler.cpp:179: Should be playing now - schedule index = 0 weekly index= 20
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:31.852 (11636) Scheduler.cpp:843: Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat, Stop (G)raceful/(L)oop/(H)ard
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:31.852 (11636) Scheduler.cpp:844: Stat Start & End Dates       Days         Start & End Times   Playlist
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:31.852 (11636) Scheduler.cpp:845: ---- ----------------------- ------------ ------------------- ---------------------------------------------
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:31.852 (11636) Scheduler.cpp:863: +  G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Christmas 2020
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:19:31.852 (11636) Scheduler.cpp:863: + *G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Static
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:23:02.197 (11636) Scheduler.cpp:179: Should be playing now - schedule index = 1 weekly index= 0
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:23:02.199 (11636) Scheduler.cpp:843: Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat, Stop (G)raceful/(L)oop/(H)ard
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:23:02.199 (11636) Scheduler.cpp:844: Stat Start & End Dates       Days         Start & End Times   Playlist
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:23:02.199 (11636) Scheduler.cpp:845: ---- ----------------------- ------------ ------------------- ---------------------------------------------
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:23:02.199 (11636) Scheduler.cpp:863: +  G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Christmas 2020
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:23:02.199 (11636) Scheduler.cpp:863: + *G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Static
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:08.003 (11636) Scheduler.cpp:722: Schedule Entry: 17:19:07 - 23:00:00 - Stopping Playlist Gracefully
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:33.402 (11636) Scheduler.cpp:179: Should be playing now - schedule index = 0 weekly index= 21
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:33.405 (11636) Scheduler.cpp:843: Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat, Stop (G)raceful/(L)oop/(H)ard
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:33.405 (11636) Scheduler.cpp:844: Stat Start & End Dates       Days         Start & End Times   Playlist
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:33.405 (11636) Scheduler.cpp:845: ---- ----------------------- ------------ ------------------- ---------------------------------------------
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:33.405 (11636) Scheduler.cpp:863: +  G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Christmas 2020
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:34:33.406 (11636) Scheduler.cpp:863: + *G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Static
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:38:03.767 (11636) Scheduler.cpp:179: Should be playing now - schedule index = 1 weekly index= 0
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:38:03.769 (11636) Scheduler.cpp:843: Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat, Stop (G)raceful/(L)oop/(H)ard
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:38:03.769 (11636) Scheduler.cpp:844: Stat Start & End Dates       Days         Start & End Times   Playlist
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:38:03.769 (11636) Scheduler.cpp:845: ---- ----------------------- ------------ ------------------- ---------------------------------------------
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:38:03.769 (11636) Scheduler.cpp:863: +  G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Christmas 2020
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:38:03.769 (11636) Scheduler.cpp:863: + *G 2018-01-01 - 2025-12-31 Everyday     17:19:07 - 23:00:00 Static
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:49:08.009 (11636) Scheduler.cpp:722: Schedule Entry: 17:19:07 - 23:00:00 - Stopping Playlist Gracefully
Dec  6 22:49:34 FPP fppd[11636]: 2020-12-06 22:49:34.963 (11636) Scheduler.cpp:179: Should be playing now - schedule index = 0 weekly index= 22
Dec  6 22:55:01 FPP CRON[18668]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec  6 22:57:50 FPP fppd[11636]: 2020-12-06 22:49:34.967 (11636) Scheduler.cpp:843: Current Schedule: (Status: '+' = Enterminate called after throwing an instance of 'std::bad_alloc'
Dec  6 22:57:50 FPP fppd[11636]:   what():  std::bad_alloc
Dec  6 22:57:50 FPP fppd[11636]: Magick: abort due to signal 6 (SIGABRT) "Abort"...
Dec  6 22:57:50 FPP systemd[1]: fppd.service: Main process exited, code=killed, status=6/ABRT
Dec  6 22:57:50 FPP systemd[1]: fppd.service: Failed with result 'signal'.
Dec  6 22:57:50 FPP systemd[1]: fppd.service: Service RestartSec=100ms expired, scheduling restart.
Dec  6 22:57:50 FPP systemd[1]: fppd.service: Scheduled restart job, restart counter is at 1.
Dec  6 22:57:50 FPP systemd[1]: Stopped FPPd.
Dec  6 22:57:50 FPP systemd[1]: Starting FPPd...
Dec  6 22:57:50 FPP fppd_boot_pre[18709]: Setup channel outputs
Dec  6 22:57:50 FPP fppd_boot_pre[18709]: Running pre-start scripts
Dec  6 22:57:51 FPP fppd_boot_pre[18709]: FPP - Turning OFF screen blanking
Dec  6 22:57:53 FPP systemd[1]: Started FPPd.
Dec  6 22:57:54 FPP fppd[18731]: terminate called after throwing an instance of 'std::bad_alloc'
Dec  6 22:57:54 FPP fppd[18731]:   what():  std::bad_alloc
Dec  6 22:57:54 FPP fppd[18731]: Magick: abort due to signal 6 (SIGABRT) "Abort"...
Dec  6 22:57:54 FPP systemd[1]: fppd.service: Main process exited, code=killed, status=6/ABRT
Dec  6 22:57:54 FPP systemd[1]: fppd.service: Failed with result 'signal'.
Dec  6 22:57:55 FPP systemd[1]: fppd.service: Service RestartSec=100ms expired, scheduling restart.
Dec  6 22:57:55 FPP systemd[1]: fppd.service: Scheduled restart job, restart counter is at 2.
Dec  6 22:57:55 FPP systemd[1]: Stopped FPPd.
Dec  6 22:57:55 FPP systemd[1]: Starting FPPd...
Dec  6 22:57:55 FPP fppd_boot_pre[18748]: Setup channel outputs
Dec  6 22:57:55 FPP fppd_boot_pre[18748]: Running pre-start scripts
Dec  6 22:57:55 FPP fppd_boot_pre[18748]: FPP - Turning OFF screen blanking
Dec  6 22:57:57 FPP systemd[1]: Started FPPd.
Dec  6 22:57:58 FPP fppd[18770]: terminate called after throwing an instance of 'std::bad_alloc'
Dec  6 22:57:58 FPP fppd[18770]:   what():  std::bad_alloc
Dec  6 22:57:58 FPP fppd[18770]: Magick: abort due to signal 6 (SIGABRT) "Abort"...
Dec  6 22:57:58 FPP systemd[1]: fppd.service: Main process exited, code=killed, status=6/ABRT
Dec  6 22:57:58 FPP systemd[1]: fppd.service: Failed with result 'signal'.
Dec  6 22:57:58 FPP systemd[1]: fppd.service: Service RestartSec=100ms expired, scheduling restart.
Dec  6 22:57:58 FPP systemd[1]: fppd.service: Scheduled restart job, restart counter is at 3.
Dec  6 22:57:58 FPP systemd[1]: Stopped FPPd.
Dec  6 22:57:58 FPP systemd[1]: Starting FPPd...
Dec  6 22:57:58 FPP fppd_boot_pre[18783]: Setup channel outputs
Dec  6 22:57:58 FPP fppd_boot_pre[18783]: Running pre-start scripts
Dec  6 22:57:58 FPP fppd_boot_pre[18783]: FPP - Turning OFF screen blanking
Dec  6 22:58:01 FPP systemd[1]: Started FPPd.
Dec  6 22:58:02 FPP fppd[18805]: terminate called after throwing an instance of 'std::bad_alloc'
Dec  6 22:58:02 FPP fppd[18805]:   what():  std::bad_alloc
Dec  6 22:58:02 FPP fppd[18805]: Magick: abort due to signal 6 (SIGABRT) "Abort"...
Dec  6 22:58:02 FPP systemd[1]: fppd.service: Main process exited, code=killed, status=6/ABRT
Dec  6 22:58:02 FPP systemd[1]: fppd.service: Failed with result 'signal'.
Dec  6 22:58:02 FPP systemd[1]: fppd.service: Service RestartSec=100ms expired, scheduling restart.
Dec  6 22:58:02 FPP systemd[1]: fppd.service: Scheduled restart job, restart counter is at 4.
Dec  6 22:58:02 FPP systemd[1]: Stopped FPPd.
```

**Comment by tielur** [comment] 2020-12-07 06:23
I had two schedules, I noticed if I go delete one it fixes this issue

**Comment by tielur** [comment] 2020-12-07 06:29
I also tried updating to `v4.5.1-5-g1f787185 (v4.5 branch)` and I get the same issue

**Comment by tielur** [comment] 2020-12-07 06:47
The error references https://github.com/FalconChristmas/fpp/blob/master/src/Scheduler.cpp#L843 which has to do with calculating sunrise/sunset. I changed my schedules to not use sunset and it's working now. So it seems something related to that calculation

**Comment by dkulp** [comment] 2020-12-07 06:50
Any chance we can get a backup of your configs with the problematic schedule so we can try reproducing?

**Comment by tielur** [comment] 2020-12-07 06:52
@dkulp I'm more then happy to provide anything that may help I just want to make sure there isn't any sensitive information in there that I may have to scrub?

**Comment by dkulp** [comment] 2020-12-07 06:57
Only thing likely would be wifi passwords.   It's just a json file so you should be able to open it up in Firefox or something and do a quick scan.

**Comment by tielur** [comment] 2020-12-07 07:10
@dkulp here you go

[FPP_all-backup_v3_20201207000958.zip](https://github.com/FalconChristmas/fpp/files/5650980/FPP_all-backup_v3_20201207000958.zip)

**Comment by tielur** [comment] 2020-12-07 07:11
If you change the start time of both of those schedules to something other then sunrise the problem goes away

**Comment by tielur** [comment] 2020-12-07 07:34
I think the issue may be time sensitive as well because it seems to run fine all day until close to midnight when it's trying to calculate when the next show time will be for tomorrow, not sure if that helps

**Comment by cpinkham** [comment] 2020-12-10 23:59
Please pull in the latest updates to make sure you are at v4.5.1-6 and see if the problem still occurs.  It looks like you are being hit by a bug in the scheduler that was fixed after v4.5.1 was released.  I don't know if that is causing the main issue but I'd like to know if pulling in the update helps.

**Comment by tielur** [comment] 2020-12-11 00:01
@cpinkham I can reproduce the error on version v4.5.1-6-gb03cf1c0

**Comment by tielur** [comment] 2020-12-11 00:04
@cpinkham is there a README or steps I can follow to compile and run the code locally to maybe help troubleshoot?

**Comment by tielur** [comment] 2020-12-11 00:05
And are you able to reproduce with my settings that I uploaded?

**Comment by cpinkham** [comment] 2020-12-11 05:43
We are looking at a v4.6 release soon and this fix will be in it.

**Closed** 2020-12-11 05:42 UTC
