### ISSUE TITLE
.htpasswd file missing

### ISSUE THREAD

**Issue by kenjreno** [FalconChristmas/fpp#591] opened 2019-11-15 16:24 UTC
Installed the Docker version of FPP, and used option 'Set UI Password'. 
Entered password and clicked Submit. Page refreshed with a 'Internal Server Error'

I tracked this down to /home/fpp/media/config/.htpasswd file was missing. 
Once I created this file, the web page was once again displayed correctly. 

This was using version:
 v3.x-master-175-g46f74190 (master branch)

**Comment by cpinkham** [comment] 2020-02-29 07:18
Can you try reproducing with the current version of FPP master code branch?  The UI password settings have moved to a different page and were partially rewritten, so I'm curious if you are still experiencing this issue.

**Comment by cpinkham** [comment] 2020-03-26 18:52
Closing this since this code has been rewritten in the master branch and we will probably not spend a lot of time tracking down an issue in an older FPP release unless someone finds the issue and submits a patch.

**Closed by cpinkham** 2020-03-26 18:52 UTC
