### ISSUE TITLE
FPPD constantly stopping when choosing a particular sequence to play in a playlist

### ISSUE THREAD

**Issue by bchiaino** [FalconChristmas/fpp#608] opened 2019-11-28 15:37 UTC
When I have my playlist running I can simply click on another sequence nd hit play and 9 times out of 10 FPPD just stops and I have to restart it. I noticed if I use the "big buttons" plugin that I can trigger all of these with no issues, its only an issue if I go on my computer and try to select them in Chrome in a playlist

here's a video showing the steps - https://youtu.be/ZaTq4qMLTHo
fppd.log - 
[fppd (12).log](https://github.com/FalconChristmas/fpp/files/3902325/fppd.12.log)

logs say the following at the time of stop

019-11-28 10:29:39.365 (3629) Scheduler.cpp:739:- * 2019-01-01 - 2021-12-02 Sun-Thurs    22:00:00 - 22:59:00 SHOWTIMES
2019-11-28 10:30:22.491 (3629) fppd.c:96:Crash handler called:  11
2019-11-28 10:30:22.492 (3629) fppd.c:102:  /opt/fpp/src() [0x145a0]
2019-11-28 10:30:22.493 (3629) fppd.c:102:  /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x74467120]
2019-11-28 10:30:22.547 (3754) fppd.c:96:Crash handler called:  11
2019-11-28 10:30:22.549 (3754) fppd.c:102:  /opt/fpp/src() [0x145a0]
2019-11-28 10:30:22.550 (3754) fppd.c:102:  /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0x74467120]
2019-11-28 10:30:34.537 (3894) log.c:227:=========================================
2019-11-28 10:30:34.537 (3894) log.c:228:FPP 3.x-master-233-g4463a9cc
2019-11-28 10:30:34.537 (3894) log.c:229:Branch: master
2019-11-28 10:30:34.537 (3894) log.c:230:=========================================
2019-11-28 10:30:34.893 (3932) channeloutput/channeloutput.c:373:UDPOutput 0:  Determined range needed 0 - 11730
2019-11-28 10:30:34.893 (3932) channeloutput/channeloutput.c:373:UDPOutput 0:  Determined range needed 11730 - 15826
2019-11-28 10:30:34.893 (3932) channeloutput/processors/BrightnessOutputProcessor.cpp:33:Brightness:   1609-1788 => Brightness:55   Gamma: 1.000000
2019-11-28 10:30:34.894 (3932) channeloutput/processors/BrightnessOutputProcessor.cpp:33:Brightness:   5335-5335 => Brightness:50   Gamma: 1.000000
2019-11-28 10:30:34.894 (3932) channeloutput/channeloutput.c:403:OutputProcessor:  Determined range needed 1608 - 1787
2019-11-28 10:30:34.894 (3932) channeloutput/channeloutput.c:403:OutputProcessor:  Determined range needed 5334 - 5334
2019-11-28 10:30:34.894 (3932) channeloutput/channeloutput.c:413:Determined range needed 0 - 15831
2019-11-28 10:30:35.058 (3932) command.c:84:Initializing Command Module
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:669:Loading Schedule from /home/fpp/media/schedule
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:720:Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat)
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:721:St  Start & End Dates       Days         Start & End Times   Playlist
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:722:--- ----------------------- ------------ ------------------- ---------------------------------------------
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:739:-   2019-01-01 - 2021-12-02 Everyday     16:44:54 - 17:56:00 15PRESHOW
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:739:- * 2019-01-01 - 2021-12-02 Sun-Thurs    17:00:00 - 21:59:55 MAIN
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:739:- * 2019-01-01 - 2021-12-02 Fri/Sat      17:00:00 - 22:59:55 MAIN
2019-11-28 10:30:35.059 (3932) Scheduler.cpp:739:- * 2019-01-01 - 2021-12-02 Sun-Thurs    22:00:00 - 22:59:00 SHOWTIMES
2019-11-28 10:30:35.063 (3932) fppd.c:620:Starting main processing loop

**Comment by dkulp** [comment] 2019-11-30 01:40
I cannot reproduce on my FPP instance with my show.   I will need to be able to remote in and run in the debugger.

**Comment by bchiaino** [comment] 2019-11-30 01:41
sounds good, ill DM you tomorrow on FB and see if you have time before my shows start again. thanks Daniel!

**Comment by ghormann** [comment] 2020-09-24 01:38
Closing old 3.x ticket that was sequence specific.  Assuming issue was resolved with Dan's help

**Closed by ghormann** 2020-09-24 01:38 UTC
