### ISSUE TITLE
BBB - F16-B - problem when set as a Remote and "Sequences" folder is empty

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#149] opened 2015-08-04 03:41 UTC
I did not load any FSEQ files onto the F16-B before testing. I had a RasPi as Master with 3 remotes (Octoscroller, F4-B and F16-B). The other Remotes did have FSEQ files loaded.

The F16-B was Stopping the FPPD and would not restart until rebooting the BBB. If the master was still playing, the F16-B would again stop the FPPD.

If the Master was not playing, the FPPD continued to run.

Copied 3 FSEQ files into the F16-B directory and never had a problem again.

**Comment by cpinkham** [comment] 2015-08-07 21:57
I will be looking as soon as we cut the v1.5 Beta images, so it will get tested/fixed in master and stage branches.

**Comment by cpinkham** [comment] 2015-08-08 08:55
I tried reproducing this tonight and couldn't make it happen.  I will try again on different systems, but it can also be retested on the FPP v1.5 Alpha images which I should have ready this weekend.

**Comment by cpinkham** [comment] 2015-09-09 05:45
I am still unable to reproduce this with current master/stage/v1.5 code.  Closing ticket until it can be reproduced again.

**Closed by cpinkham** 2015-09-09 05:45 UTC
Labels: bug
