### ISSUE TITLE
fppd went idle during schedule

### ISSUE THREAD

**Issue by joeharrison714** [FalconChristmas/fpp#902] opened 2020-12-04 02:12 UTC
**FPP Version and Hardware**:  FPP 4.5.1 running on Pi 3B+

**Expected behavior**: 
fppd ended gracefully and did not play scheduled playlist

**Additional context**: 
At 5:15 pm the "On Demand Mode" playlist started as scheduled and was scheduled to run until 5:59:59.
At about 5:55 PM I did an "Insert Playlist Immediate" of "Playlist Night 2"
At 6:00 pm the "Playlist Night 2" playlist was scheduled to start.
At about 6:03, the inserted playlist ended gracefully before it was over and then the player sat idle.
I restarted fppd and the schedule kicked back in.
[fppd.log](https://github.com/FalconChristmas/fpp/files/5640142/fppd.log)

 Log attached

**Comment by cpinkham** [comment] 2020-12-04 03:46
This may have been fixed by the scheduler changes I pushed to the master branch today.  I think there were two related situations where a scheduled playlist may have been prematurely set to Stopping Gracefully if the preceeding scheduled playlist was manually interrupted.  I didn't test this exact scenario with inserting a playlist, but it could be related.  I doubt we will pull this patch back to a release branch for a while since it is a bit invasive.  I did want to give a heads up that this may be fixed.

**Comment by marciuliani** [comment] 2020-12-04 03:56
Chris,

If it's any consolation - I updated before tonight's show and it ran fine - it's the last playlist of the schedule before tomorrow's new playlist kicks in.  I'm running FPP as a master and 2 remotes - 1 on a 36 panel p10 matrix and another 4 p10 panel tune to sign.  


Thanks for the updates 

Marc

**Comment by joeharrison714** [comment] 2020-12-04 19:45
@cpinkham Thanks for all the work you do on this project!

I switched to the master branch to test this. Unfortunately, I was able to reproduce the problem. Also, I misspoke in my original report. The player does not go idle but actually it just stops playing completely. I have created a video demonstrating the problem:
https://www.youtube.com/watch?v=WMR27KQpF80

Let me know if there is any other way I can be of assistance on this.

**Comment by cpinkham** [comment] 2020-12-11 00:07
Are you running the Remote Falcon plugin?  We found an issue with that a little earlier this week where it prematurely stops running playlists.

According to the fppd.log, the scheduler was actually running right as you restarted fppd, so I'm not sure if it was about to do something or what.

=====================================================================
2020-12-03 18:03:14.061 (25050) Scheduler.cpp:839: Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat, Stop (G)raceful/(L)oop/(H)ard
2020-12-03 18:03:14.062 (25050) Scheduler.cpp:840: Stat Start & End Dates       Days         Start & End Times   Playlist
2020-12-03 18:03:14.062 (25050) Scheduler.cpp:841: ---- ----------------------- ------------ ------------------- ---------------------------------------------
2020-12-03 18:03:14.062 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Day Mask     18:00:00 - 21:00:00 Playlist Night 1
2020-12-03 18:03:14.062 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Day Mask     18:00:00 - 22:00:00 Playlist Night 1
2020-12-03 18:03:14.062 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Day Mask     18:00:00 - 21:00:00 Playlist Night 2
2020-12-03 18:03:14.063 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Day Mask     18:00:00 - 22:00:00 Playlist Night 2
2020-12-03 18:03:14.063 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Day Mask     21:00:10 - 22:00:00 On Demand Mode
2020-12-03 18:03:14.063 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Day Mask     22:00:10 - 23:00:00 On Demand Mode
2020-12-03 18:03:14.063 (25050) Scheduler.cpp:859: + *G 2020-12-01 - 2020-12-31 Everyday     17:15:00 - 17:59:59 On Demand Mode
2020-12-03 18:03:14.063 (25050) fppd.c:683: Shutting down main loop.
=====================================================================

The scheduler normally prints that output as it takes actions.  if you can reproduce the problem, can you set your Log Level to Debug and turn on Playlist and Scheduler logging so we can see what the scheduler and player were doing at the time?

**Comment by joeharrison714** [comment] 2020-12-17 16:36
@cpinkham I just updated to the latest commit from master (b5f24ac) and unforunately I am still able to reproduce the problem. I have attached the debug log with playlist and scheduler logging. Please let me know how else I can help.

Important times:
11:22:54 - I executed insert playlist immediate command
11:23:59 - began stopping gracefully (despite inserted playlist not finished)
11:24:29 - completely locked up (not playing anything, status window showed playlist but no time was elapsing)

[fppd.log](https://github.com/FalconChristmas/fpp/files/5710823/fppd.log)

**Comment by joeharrison714** [comment] 2020-12-17 23:00
Based on some additional testing, I can simplify the problem description: If a playlist is Inserted and is still running when a schedule is ending, then the inserted playlist gets stopped and fppd gets stuck

**Comment by cpinkham** [comment] 2020-12-20 00:10
Thanks, that info should help us reproduce the issue and get a fix created.

**Closed** 2023-01-24 11:30 UTC
