### ISSUE TITLE
Descriptions for e1.31 universes cannot have special characters

### ISSUE THREAD

**Issue by dkulp** [FalconChristmas/fpp#475] opened 2018-12-04 20:31 UTC
commas and & and such will make it so the universes will not save

**Comment by cpinkham** [comment] 2018-12-04 21:08
Commas and lots of other characters now work with the new JSON file
format, but it looks like we still need to escape to handle the &

On Tue, 2018-12-04 at 12:31 -0800, Daniel Kulp wrote:
> commas and & and such will make it so the universes will not save
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/FalconChr
istmas/fpp","title":"FalconChristmas/fpp","subtitle":"GitHub
repository","main_image_url":"https://assets-cdn.github.com/images/em
ail/message_cards/header.png","avatar_image_url":"https://assets-
cdn.github.com/images/email/message_cards/avatar.png","action":{"name
":"Open in
GitHub","url":"https://github.com/FalconChristmas/fpp"}},"updates":{"
snippets":[{"icon":"DESCRIPTION","message":"Descriptions for e1.31
universes cannot have special characters
(#475)"}],"action":{"name":"View
Issue","url":"https://github.com/FalconChristmas/fpp/issues/475"}}}
> [
> {
> > "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> > "target": "https://github.com/FalconChristmas/fpp/issues/475",
> > "url": "https://github.com/FalconChristmas/fpp/issues/475",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> > "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> > "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> > "title": "Descriptions for e1.31 universes cannot have special
characters (#475)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**Daniel Kulp**",
> > "activityImage": "https://assets-cdn.github.com/images/email/message_
cards/avatar.png",
> "activitySubtitle": "@dkulp",
> "facts": [
> {
> "name": "Repository: ",
> "value": "FalconChristmas/fpp"
> },
> {
> "name": "Issue #: ",
> "value": 475
> }
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > > > "body": "{\n\"commandName\":
\"IssueComment\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 475,\n\"IssueComment\":
\"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
\"FalconChristmas/fpp\",\n\"issueId\": 475\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> > "uri": "https://github.com/FalconChristmas/fpp/issues/475"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> > "target": "https://api.github.com",
> > "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
419810688\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]

**Comment by ghormann** [comment] 2019-03-04 22:38
Duplicate of #499 which has already been closed.

**Closed** 2019-03-04 22:53 UTC
