### ISSUE TITLE
FPPD Remote stopping while playing repeated test sequences

### ISSUE THREAD

**Issue by JonB256** [FalconChristmas/fpp#244] opened 2016-08-08 12:33 UTC
As described in the FalconChristmas forum, 
http://falconchristmas.com/forum/index.php/topic,4778.msg55169.html#msg55169

I was helping another user troubleshoot and set up my own test. On two virtually identical RasPi3 running a P10 matrices, the FPPD will just stop. It is not logged as a stop in the FPPD log files, I increased the error logs to Info and Most.

What I see is that, after playing a pair of FSEQ files over and over, at 23:13:49 last night, it showed an "Error opening sequence file...."   Again, no entry for stopping, but that is probably when it stopped (I was asleep, so don't know for sure) If necessary, I can point my my security camera at the panel to find an exact time.

2016-08-07 23:13:49 (21675) Sequence.cpp:155:Error opening sequence file: 2015 Elvis Blue Christmas.fseq. Incorrect File Format header: '', bytesRead: 4

My question would be - if an error like this can stop the FPPD "mid-show" for no apparent reason (because it will restart without problem), can the FPPD be updated to retry loading the FSEQ file a few times before giving up?

Again, this is a RasPi 3B, running a Matrix Hat and 3x3 P10 setup. Running latest v1.8 
Version: v1.8-20-gaff9426

**Comment by JonB256** [comment] 2016-08-19 19:19
After chatting with another person, it occurred to me that playing a Playlist from the Status window was not how a show normally runs. You use a schedule.

So I created a schedule for my playlist. Oddly, it seems to not be stopping the FPPD. I'll continue the test run to be sure.

It may be excessive, but I now have six remotes running. There are three RasPi 3B, one RasPi B, one RasPi 2B and one BeagleBone with an F4B cape. The master makes it seven and it is a RasPi B+

A mix of eth0 and wlan0 outputs.

**Comment by JonB256** [comment] 2016-08-19 19:22
Spoke too soon. One of the RasPi 3 remotes just stopped. It is driving a P10 output and using eth0. Run time was less than two hours.

**Comment by JonB256** [comment] 2016-08-19 19:25
Then, five minutes later, the other RasPi 3 remote driving the other P10 stopped. It is using wlan0.
Restarted FPPD and watching.

**Comment by JonB256** [comment] 2016-08-19 22:05
This is a log file (Debug, ALL set) from a RasPi3 running as a Remote, driving a P10.
I had a camera recording so that I'd know EXACTLY when it quit, but the camera shut off at 1626 and I was outside. I noticed it at 1700, so sometime between 4:30pm and 5:00pm the FPPD shut itself off. It was playing the same FSEQ file over and over. A playlist was running per a schedule. 

[FPP_Logs_20160819.2159.zip](https://github.com/FalconChristmas/fpp/files/427960/FPP_Logs_20160819.2159.zip)

**Comment by JonB256** [comment] 2016-09-04 02:11
This problem seems isolated to multi-core RaspPi models. I'll put a Pi Zero back in the mix to be sure (since it is single core), but NONE of my RaspPi B or B+ or BBB or BBG units suffer from this random stopping of the Remote FPPD.

Of the multicores (Pi 2 and Pi 3), it is a random mix of eth0 or wlan0, some have Hats, some don't.

**Comment by cpinkham** [comment] 2016-09-04 23:48
Thanks for the debugging.  This issue is high on my ToDo list.  I will put my Pi v2 in remote mode and see if I can catch the issue occur while running under a debugger.

Chris

**Comment by JonB256** [comment] 2016-09-05 14:42
The PiZero (single core but newer processor) is still going (FPPD Running sequences)

**Comment by ihbar** [comment] 2016-09-05 16:43
@JonB256 
To confirm that issue is related to multicore, you can also limit the number of core used on the Pi2 and 3 to 1.   (I think you need to edit /boot/cmdline.txt and add maxcpus=1)
This will not solve the issue, but may confirm it is multicore issue. 

@chris 
I faced similar problem last year, but stoped investigation because only me was facing the issue, If you think it is usefull, I can rebuild the old setup and try to collect information. Just tell me.

Stephane

**Comment by cpinkham** [comment] 2016-09-05 16:58
I think I remember telling some people to limit cores to 1 but I was thinking that was audio related.  It does sound like a threading issue though.  I need to try to reproduce the issue on a multi core system under gdb.  I think we probably need a lock around some variable.

Chris

**Comment by JonB256** [comment] 2016-09-05 18:22
> @JonB256 
> To confirm that issue is related to multicore, you can also limit the number of core used on the Pi2 and 3 to 1. (I think you need to edit /boot/cmdline.txt and add maxcpus=1)
> This will not solve the issue, but may confirm it is multicore issue.

I did add maxcpus=1 in the cmdline.txt file. Saved, rebooted. But it isn't rebooting. :(  I never get a web interface and Putty won't connect. (so, difficult to go "back" )

**Comment by cpinkham** [comment] 2016-09-06 05:20
If you put the SD card in your regular PC, you can edit the cmdline.txt
file from there using wordpad or some other text editor which won't
insert newlines into the file.  The cmdline.txt file resides on a FAT
partition which can be mounted under Window and OS/X.

**Comment by JonB256** [comment] 2016-09-06 12:23
Chris, I can see three other partitions on the SD card, (in Win10 64bit), but cannot open or mount them in Computer Management/Disk Management. There is a recovery.cmdline file in the readable partition, but its contents are not the same as the cmdline.txt file I modified using sudo nano. (I did not use BASH)

**Comment by cpinkham** [comment] 2016-09-06 13:58
Sorry, that is another side effect of using NOOBS that I wasn't thinking about.  Without NOOBS there is only one FAT file system.

Chris

**Comment by cpinkham** [comment] 2016-09-06 20:15
I setup a Master/Remote test last night with the remote fppd running under the gdb debugger.  This morning when I checked in on them, I found that fppd on the the Pi v2 B remote had died overnight, so I was able to get a partial backtrace.  I captured that and restarted the remote fppd to see if it happens again and gives something similar.  Based on the logs and the backtrace, I think this is a race condition between the sequence finishing on the remote and the master telling the remote to stop playing because the sequence finished on the master.  I think we will need some better locking in the playback and sync code on the remote.

**Comment by JonB256** [comment] 2016-09-07 14:16
Setting maxcpus=1 does seem to stop this, but I'm driving P10 panels with the Pi 3 and I see some lagging when running a single core.

**Comment by cpinkham** [comment] 2016-09-07 18:15
The fppd crash happened again last night and it was at the same point in
the sync process.  It happened right when the sequence was stopping.  I
can see two log entries on the remote, one from the sync process running
the stop sequence command from the master and the other entry from the
"sequence completed" code.  This is definitely a race condition and I
should be able to get this fixed rather quickly by checking and fixing
the locking.

**Comment by JonB256** [comment] 2016-09-13 23:42
Chris, if you get this into one of the Master branches, let me know and I'll test.

**Comment by cpinkham** [comment] 2016-09-17 19:27
My remote has been playing in sync with my master non-stop for about 14 hours now and fppd is still running, so the fix is looking good so far.  I will check back on it tonight and if everything is still good, I will try to get the fix pushed to v1.8 this weekend.

**Comment by JonB256** [comment] 2016-09-18 11:19
Chris, I installed  the update and started my test sequence. My Pi 2 FPPD stopped  after 40 minutes. My Pi 3 stopped soon after.

**Comment by JonB256** [comment] 2016-09-18 20:14
So, I switched the Pi 2 and Pi 3 (all 4 cores running) back to the newest Master-v.1x rev. The FPPD is running fine and also running for over 7 hours on both (and the Pi 2 is worse about stopping than the 3)

**Comment by JonB256** [comment] 2016-09-19 13:01
All multi-core FPPDs are still running fine using Master-v1.x latest rev

**Comment by cpinkham** [comment] 2016-09-20 13:53
Fixed by 534ea1036284f in master-v1.x, merged to v1.8 branch, and will be rolled into next binary build in v1.8.  Closing this ticket.

**Closed by cpinkham** 2016-09-20 13:53 UTC

**Comment by thekuai** [comment] 2016-11-05 02:48
I am plagued with the same issue. Can someone tell me how to add maxcpu=1 or how to download and install master-v1.x onto my Rpi 3?

**Comment by cpinkham** [comment] 2016-11-05 04:17
I believe this issue was fixed a while back, are you running the latest v1.8 or v1.9 code?

Chris

**Comment by thekuai** [comment] 2016-11-05 04:22
I was still plagued with 1.8 and I just recently updated to 1.9. I have a
small 5 second sequence on repeat to 2 remote Pi's. All of them are pi3
model Bs...all have logging down to warn and no check boxes.
