### ISSUE TITLE
FPP reboot issue when doing a subsequent manual config change.

### ISSUE THREAD

**Issue by Tolnari** [FalconChristmas/fpp#669] opened 2020-02-07 03:22 UTC
FPP will reboot  when making a manual configuration change after uploading a config from xlights. FPPD restarts were done after each config change, as prompted in the UI

I can reliably reproduce an FPP reboot when I make a manual configuration change in the Channel Output, Pixel strings configuration after doing a xlights configuration upload. It doesn't matter what value I change. The reboot happens when restarting FPPD when prompted.

Specific sequence:
upload via xlights and restart fppd, as prompted.
manually change the  the config and restart fppd, as prompted, and it reboots.

I can make several manual changes, restart FPPD and it does not reboot.
I can also make multiple changes via xlights and upload the config, restart FPPD and it does not reboot.
The key here is the sequence of using xlights to configure the device, then perform a manual configuration change.

Logged actions:
02-06 20:23
manually changed port 2 pixel count from 101 to 100
save
restart fppd
	no reboot

02-06 20:24
upload an xlights config. Forcing port 2 pixel count from 101 to 100.
refreshed browser - FPP indicated a fppd restart was needed.
restart fppd 
	No reboot

02-06 20:27
manually changed port 2 pixel count from 100 to 101
save 
restart fppd 
	Reboot

Port 1 has a Channel block with 9 strands - ws2811 protocol (Pixel2AC board)
Port 2 has a string of 100 Pixels - ws2811 protocl

Xlights 2020.2 (WIndows, 64bi)
FPP with PiHat v3.6.1-2-gadd4fa3c
Pi is a 3B+ with a C10 SD card, powered by a 5V, 20A supply

I put logging into debug mode and grabbed all fpp  logs. Including /var/log/messages and syslog

[FPP_reboot_with_manual_config_change_logs.zip](https://github.com/FalconChristmas/fpp/files/4168807/FPP_reboot_with_manual_config_change_logs.zip)

**Comment by Tolnari** [comment] 2020-02-07 03:24
Ooops. 
![Screenshot_2020-02-06 Falcon Player - FPP status page](https://user-images.githubusercontent.com/850376/73998384-14d0c580-4927-11ea-98cd-cb76155a726d.png)
![xlights layout screen 2020-02-06](https://user-images.githubusercontent.com/850376/73998386-15695c00-4927-11ea-8755-6ecc28409a08.png)
![xlights setup screen 2020-02-06](https://user-images.githubusercontent.com/850376/73998387-15695c00-4927-11ea-8848-478e625dad23.png)


Forgot screenshost.

**Comment by ghormann** [comment] 2020-10-07 00:22
Closing as  this is on FPP 3.  If this is reproduceable in FPP4, please comment and will reopen.   

Took a quick scan of the logs and didn't see an obvious root cause, though messages like this suggest a possible file system issue.  They are detected right after boot and not at the time of the crash. 
Feb  5 02:12:50 FPP kernel: [    5.648782] F2FS-fs (mmcblk0p3): Magic Mismatch, valid(0xf2f52010) - read(0x0)
Feb  5 02:12:50 FPP kernel: [    5.650243] F2FS-fs (mmcblk0p3): Magic Mismatch, valid(0xf2f52010) - read(0x0)
Feb  5 02:12:50 FPP kernel: [    5.650288] F2FS-fs (mmcblk0p3): Magic Mismatch, valid(0xf2f52010) - read(0x0)
Feb  5 02:12:50 FPP kernel: [    5.650306] F2FS-fs (mmcblk0p3): Magic Mismatch, valid(0xf2f52010) - read(0x0)

**Closed by ghormann** 2020-10-07 00:22 UTC
