### ISSUE TITLE
DPI Pixel output on Raspberry pi4 not working

### ISSUE THREAD

**Issue by bloojoop** [FalconChristmas/fpp#1260] opened 2022-03-23 03:46 UTC
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
FPP version 6.x-master-141-g2cd2da67
OS v2022-03
Raspberry Pi 4 2 GB rev 1.4 and Pi 4 4GB rev 1.4

**Describe the bug and Steps to reproduce**: 
Goto the channel out tab, select Pixel strings.
set cape type to DPIPixel-2 pihat compatible. 
set port 1 to 50 pixels and enable output. 
select save and then restart fppd (will actually do a reboot). 
Go to display testing and enable testing (channels 1-150). 
No output will be observed.  If trying to go back to the channel output page, it will not likely get there (just browser spin).  It may show up like 15-20 minutes later or may not. 
Also try to restart fppd again and fppd will never show restarted.  

**Expected behavior**: 
Expected behaviour would be to do display testing and everything on the Pi would continue to respond and function normally

**Additional context**: 
this has been a problem since the introduction of the dpi pixel output type.  I imaged fresh with the new alpha 3 image and updated to tonights most recent commits and retested.  I can screen share or run debug code or whatever is needed to help identify and resolve this issue. 

**Additional Attachments**
log files attached. 

[FPP_Logs_20220323.0333.zip](https://github.com/FalconChristmas/fpp/files/8329533/FPP_Logs_20220323.0333.zip)

**Comment by cpinkham** [comment] 2022-03-24 03:21
I will be borrowing a Pi 4 from a local FPP user and should be checking this out in the next few days.

**Comment by bloojoop** [comment] 2022-03-24 03:42
@cpinkham , Awesome.. My offer to ship one to you for testing still stands as well, in case your local resource doesn't pan out.

**Comment by fone626** [comment] 2022-03-27 23:15
I hadn't actually tested my board on a PI4 yet, so this got me wondering... so I sacrificed a security camera to the holiday lighting gods and tore the PI4 out of it and sure enough I get exactly the same behavior with no output, and not being able to get back the the output page... but in my case with DPIPixels-24
kern.log shows the following immediately after I click the testing button:
Mar 27 16:13:47 FPP kernel: [   53.034661] bcm2708_fb soc:fb: ioctl 0x40044620 failed (-110)
Mar 27 16:13:48 FPP kernel: [   54.074695] cpu cpu0: dev_pm_opp_set_rate: failed to find current OPP for freq 4294967186 (-34)
Mar 27 16:13:50 FPP kernel: [   56.154704] bcm2708_fb soc:fb: Failed to allocate GPU framebuffer (-110)
Mar 27 16:13:50 FPP kernel: [   56.154721] bcm2708_fb_pan_display(0,162) returns=-110
Mar 27 16:13:52 FPP kernel: [   58.234675] raspberrypi-clk soc:firmware:clocks: Failed to change fw-clk-arm frequency: -110

**Comment by cpinkham** [comment] 2022-03-29 06:22
I was able to reproduce this.  I think I know what is happening and am researching to see if there is a config-based solution before I code a workaround in FPP.

**Comment by bloojoop** [comment] 2022-03-31 17:53
That's awesome news Chris!  thanks for all your (and others) work on this project!

**Comment by bloojoop** [comment] 2022-05-04 02:31
@cpinkham , Hey Chris, I've been tied up for several weeks on other tasks.. I'm getting back to my v6 testing.  I was just curious of the status of this fix for dpi pixels.  I'm sure you all have been quite busy, so just curious as to when this fix may get pushed ?  Thanks again for all your effort !!

**Comment by cpinkham** [comment] 2022-05-26 05:23
This was fixed in 70a4dfd005

**Comment by cpinkham** [comment] 2022-06-17 05:05
Reopening this since there is a color shift issue part of the way down the string on a Pi 4.  I need to double check to make sure nothing was missed when I merged the patch over from my Pi 4 to my main dev Pi 3 and possibly may need to look at adjusting the DPI timings line if everything else looks OK.

**Closed** 2022-06-17 06:22 UTC
Labels: bug
