### ISSUE TITLE
fpp 4.3 will not run smart receiver boards on the kulp f32b they flash all white  switch back to fpp4.2 works fine 

### ISSUE THREAD

**Issue by rushkd** [FalconChristmas/fpp#835] opened 2020-10-18 05:24 UTC
running a BBB with a kulp f32b, when i upgraded to fpp 4.3 it made my two smart receiver boards  hooked together off the first rj45 jack come on all white as soon as fpp loaded, the only way to turn them off is to shut the player off , but as soon as the player comes back on they light back up. switched back to fpp 4.2 and the problem goes away.    

[FPP_Logs_20201018.0513.zip](https://github.com/FalconChristmas/fpp/files/5397080/FPP_Logs_20201018.0513.zip)
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 4.2 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the FOn the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by darylc** [comment] 2021-06-05 08:43
@dkulp Seems we'd have a bunch of people complaining if this issue still existed?  Shall we close this?

**Comment by dkulp** [comment] 2021-06-11 18:31
Cannot reproduce.

**Closed by dkulp** 2021-06-11 18:31 UTC
