### ISSUE TITLE
FPP Pi Pixel String Outputs do not work with Version 4.3

### ISSUE THREAD

**Issue by ahallber** [FalconChristmas/fpp#834] opened 2020-10-17 05:02 UTC
Using a Pi 3 with a PixelController.com Pi Cap, the 2 pixel string outputs do not work when I converted from 4.1 to 4.3. I reverified that the 2 outputs worked in version 3.5 and 4.1; but they did not work with the 4.3 upgrade

I attached a picture of the Pi Pixel Setup that is used.

![4 1 Pi Pixel Strings setup](https://user-images.githubusercontent.com/40327848/96328733-d63def80-100b-11eb-8cf8-18d7abafac27.PNG)
.

**Comment by ghormann** [comment] 2020-10-20 10:18
@ahallber : 
1) Do the pixels work in Test model (Status/Control->Display Testing)?
2) Can you attach the log files?

**How to attach Logs**
1. Open the FPP UI
2. Open the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by ahallber** [comment] 2020-10-21 04:51
Hi Greg,

Thanks for your help with this. With the version 4.3, the pixels that were connected to the Pi Cap did not light up in Test Display mode. I did some additional testing after I logged the issue on github and will do my best to articulate what I observed...I hope this helps.

- I ran some tests on the show Pi controller and a test Pi controller (pictures attached). These are 2 different Pi Controllers and 2 different caps. Both are Pi3 with Pixel Controller.com caps. The only difference between the two is the Show controller is wired with a 5v power supply to power the Pi and with a 12v power supply running the cap for the pixel output; both the Pi and the Cap on the test controller are powered from the 12v power supply. The power jumpers on the show and test controllers are set accordingly.
- I had 1 SD card with the 4.1 image, and 1 SD card with the 4.3 image. The logs for both are attached, and the logs were downloaded when both SD cards were installed and running in the show Pi controller.

As noted in the original issue that was log on github, when I installed version 4.3 on the show Pi controller (via a complete reimage from the file on github), the pixels wired to the 2 cap outputs did NOT light when enabled in the Pi's Display test mode. I have a F16v3 plugged into the Show Pi controller on the etho output, and the lights plugged into the F16v3 did light up when the Pi's Display Test Mode was enabled with the 4.3 image. I put the SD card with the 4.1 image on the show Pi controller and the pixels connected to the cap did light up when enabled in the Pi's Display test mode.

After I logged the issue in github, I put the same SD card with the 4.3 image into my test Pi Controller. Interestingly enough, the lights plugged in to the 2 cap outputs DID light up.

I rewired the power on the test Pi Controller to the same configuration as the show controller (changing the power jumpers on the test controller cap accordingly), and the lights plugged into the 2 cap outputs DID light up with the 4.3 image.

I ran another test on the show Pi controller and again, with the 4.1 image, the lights on 2 cap outputs DID light up; but with the 4.3 image was tested again, the lights on the 2 cap outputs did NOT light up.

One other observation...When I initially accessed the Falcon Player Display testing screen with both the 4.1 and 4.3 images on the show controller after a reboot:
- the start channel and ending channel with the 4.1 image were 97 and 144 respectively (see attached picture). I raised the end channel to 300000 which is currently above the last output called out in the Channel Output Setup menu on the 4.1 image, and that is when the lights came on when the Pi Display testing screen was enabled
- the start channel and ending channel with the 4.3 image displayed 97 and 234328 respectively (see attached picture). 234328 represents the last channel called out in the Channel Output Setup menu on the 4.3 image. Even when I adjusted the last channel field to a higher value, the lights connected the cap would NOT come on when the Pi Display testing screen was enabled.

Hope this helps...thanks again,

Allen




________________________________

**Comment by ahallber** [comment] 2020-10-21 04:57
see attached logs


________________________________

**Comment by ahallber** [comment] 2020-10-21 04:58
see attached pictures


________________________________

**Comment by ghormann** [comment] 2020-10-21 10:24
@ahallber : The pictures and files didn't actually attach via email.   You'll need to log into github and attach them.   You might also consider jumping into the zoom meeting and seeing if someone can help as this is a rather complex issue and the swapping of the cards will make it difficult to figure out what is going on in the logs.

**Comment by patdelaney** [comment] 2020-10-21 11:05
Reach out to me directly and we can do a Zoom call. I am not seeing this
behavior.
pat_delaney@colonydrive.com   also backup your PI configuration and attach
it here.

Thanks

**Comment by ahallber** [comment] 2020-10-22 04:07
Thanks Greg. I have reached out to Pat to see if we connect on Zoom.

thanks,
Allen


________________________________

**Comment by patdelaney** [comment] 2020-10-22 14:40
For those following this issue, I am going to close it because the title is misleading. Pixel String Outputs on Pi are not broken in 4.3. The backup config file that the user restored from has an issue that I am currently trying to pin point. I am able to reproduce the issue with his backup config json file. If I import the file into my lab and try to do display testing. The lights do not light as the user had reported. If I go to the Channel outputs and simply hit Save on the E1.31 page and restart fppd then go back to display testing then the lights work. There appears to be something mal-formed in the json backup file, that clicking save in channel outputs fixes.

**Closed by patdelaney** 2020-10-22 14:40 UTC
