### ISSUE TITLE
FPP audio reverts to dummy after rebooting FPP

### ISSUE THREAD

**Issue by striker72** [FalconChristmas/fpp#1684] opened 2023-12-01 00:18 UTC
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**:   Raspberry Pi 3B running 
FPP Version: | 7.3.5
Platform: | Raspberry Pi (Pi 3 Model B)
![audio settings](https://github.com/FalconChristmas/fpp/assets/27774858/10ed1193-616b-4de1-870a-0c19481d720e)

FPP OS Build: | v2023-11
OS Version: | Raspbian GNU/Linux 11 (bullseye)

runnning on hanson [rPI-28D+] (https://www.hansonelectronics.com.au/product/rpi-28dplus/)

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Go to '...'  Status Control, FPP Settings, Audio / Video, 
2. Click on '....'Audio Output Device
3. Scroll down to '....' on reboot, it switches from USB Audio Device to Dummy and i get no sound from the props until i go here and switch it back to USB Audio device and then reboot again.  
4. See error.  No error, just reverts audio output to dummy on reboots.

**Expected behavior**: 
A clear and concise description of what you expected to happen and why.  I have been running this same hardware for 2 years and  never had this issue before.  The only thing I did differently this year was to upgrade FPP to 7.3.5 from 6.x I was using last year.  I am not sure what the issue is but i am hoping you can assist me to fix it.

Log files attached.  Let me know if you need anything else.  Thank you so very much. 

**Additional context**: 

**Additional Attachments**
Please include the log files. To create the file:
1. Open the FPP UI
2. Open the the File Manager (Content Setup->File Manager), 
3. Select the "Logs" tab
4. Click "zip" button.
5. Attach to this ticket.

**Comment by striker72** [comment] 2023-12-01 00:19
[FPP_Logs_20231130.2341.zip](https://github.com/FalconChristmas/fpp/files/13518959/FPP_Logs_20231130.2341.zip)

**Comment by striker72** [comment] 2023-12-01 00:25
I was browsing the logs and i noticed this, not sure if this helps or not from Apache2-error.log

Thu Nov 30 18:19:50.546447 2023] [proxy_fcgi:error] [pid 1581:tid 1615836160] [client 192.168.10.108:56976] AH01071: Got error 'PHP message: PHP Fatal error:  **_Uncaught Error: Call to undefined function SetAudioOutput() in /opt/fpp/www/api/controllers/settings.php:119\nStack trace:\n#0 /opt/fpp/www/api/lib/limonade.php(430): PutSetting()\n#1 /opt/fpp/www/api/index.php(181): run()\n#2 {main}\n  thrown in /opt/fpp/www/api/controllers/settings.php on line 119', referer: http://192.168.10.100/settings.php_**
[Thu Nov 30 18:37:53.083509 2023] [proxy_fcgi:error] [pid 1242:tid 1518306304] [client 192.168.10.74:44815] AH01071: Got error 'PHP message: PHP Warning:  unpack(): Type a: not enough input, need 26, have 0 in /opt/fpp/www/co-pixelStrings.php on line 2478', referer: http://192.168.10.100/about.php

**Comment by Rarefy-Dev** [comment] 2023-12-02 03:41
I am having the same issue.

FPP Version: | 7.3.5
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v2023-11
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Kernel Version: | 6.1.21-v7+

runnning on Falcon 16 v4

Describe the bug and Steps to reproduce:
A clear and concise description of what the bug is and the steps to be taken to reproduce.

Go to '...' Status Control, FPP Settings, Audio / Video,
Click on '....'Audio Output Device
Scroll down to '....' on reboot, it switches from USB Audio Device to BCM2835 Headphones and i get no sound from the props until i go here and switch it back to USB Audio device and then reboot again.
See error. No error, just reverts audio output to dummy on reboots.

Expected behavior:
A clear and concise description of what you expected to happen and why. I have been running this same hardware for 2 years and never had this issue before. The only thing I did differently this year was to upgrade FPP to 7.3.5 from 6.x I was using last year. I am not sure what the issue is but i am hoping you can assist me to fix it.

Log files attached. Let me know if you need anything else. Thank you so very much.

Additional context:
Add any other context about the problem here.

Additional Attachments
Please include the log files. To create the file:

Open the FPP UI
Open the the File Manager (Content Setup->File Manager),
Select the "Logs" tab
Click "zip" button.
Attach to this ticket.
If applicable, add screenshots to help explain your problem.

**Comment by Rarefy-Dev** [comment] 2023-12-02 03:41
[FPP_Logs_20231202.0339.zip](https://github.com/FalconChristmas/fpp/files/13533268/FPP_Logs_20231202.0339.zip)

**Comment by Rarefy-Dev** [comment] 2023-12-02 03:46
I also am seeing an error in SetAudioOutput in the above logs.


[Sun Nov 26 17:16:58.249146 2023] [proxy_fcgi:error] [pid 1263:tid 1686086656] [client 10.0.0.46:50544] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function SetAudioOutput() in /opt/fpp/www/api/controllers/settings.php:119\nStack trace:\n#0 /opt/fpp/www/api/lib/limonade.php(430): PutSetting()\n#1 /opt/fpp/www/api/index.php(181): run()\n#2 {main}\n  thrown in /opt/fpp/www/api/controllers/settings.php on line 119', referer: http://10.0.0.120/settings.php

**Comment by striker72** [comment] 2023-12-02 19:20
No I have not but will try that. Thanks. Regards,CraigOn Dec 2, 2023, at 1:56 PM, Daryl ***@***.***> wrote:﻿
Have you tried going into fpp settings -- system and add 5 second fppd boot delay. Sometimes fpp needs a bit of a delay for the os discover functions to work.

**Comment by Rarefy-Dev** [comment] 2023-12-02 19:30
No. Will try that tonight.  Thank you.

**Comment by Rarefy-Dev** [comment] 2023-12-04 23:27
Two days in a row, not having the issue after moving it to 5 second boot delay.   Thank you.

MH

**Comment by striker72** [comment] 2023-12-05 00:08
Same here. Regards,CraigOn Dec 4, 2023, at 6:27 PM, Mark Hall ***@***.***> wrote:﻿
Two days in a row, not having the issue after moving it to 5 second boot delay.   Thank you.
MH

**Comment by cpinkham** [comment] 2023-12-05 02:46
I believe we still have code in the startup process where FPP checks the audio device at to make sure it is valid and reverts.  Adding the delay let’s the card initialize before fppd starts.ChrisOn Dec 4, 2023, at 4:08 PM, striker72 ***@***.***> wrote:﻿
Same here. Regards,CraigOn Dec 4, 2023, at 6:27 PM, Mark Hall ***@***.***> wrote:﻿

Two days in a row, not having the issue after moving it to 5 second boot delay.   Thank you.

MH

**Comment by cpinkham** [comment] 2023-12-05 21:28
We are looking at adding a default slight delay on multi-core systems because of this and other issues where the multi-core Pi startup so fast that fppd starts before some other parts of the system like USB devices or NTP time sync.

Closing this ticket as the user's issue has been resolved.

**Closed by cpinkham** 2023-12-05 21:28 UTC
