### ISSUE TITLE
SD Card not mounting as storage when booting from BBB eMMC

### ISSUE THREAD

**Issue by compufritz** [FalconChristmas/fpp#1731] opened 2023-12-20 21:28 UTC
# Please answer the following:
**FPP Version and Hardware**: 
Example: *FPP 7.4 running on BBB*

**Describe the bug and Steps to reproduce**: 
A clear and concise description of what the bug is and the steps to be taken to reproduce. 
1. Fresh format and burn ISO onto SD Card. Install and boot system.
2. Complete Initial Setup and reboot system.
3. On Storage tab under FPP settings, click the button to Flash to eMMC and allow to complete.
4. Power of the system, remove the SD card and format with SD Formatter. Re-install SD card and power on the system.
5. Change UI in FPP Settings to 'Advanced'. Click on 'Storage' tab and change storage option in drop-down to the SD card.
6. Error pops up stating 'Failed to save storage Device setting' and the SD card shows as 'Not Mounted' in the drop-down menu.

**Expected behavior**: 
Upon reboot with formatted SD card, expect the system to mount the SD card as a storage partition and allow it to be selected as a storage option.

**Additional context**: 
Reviewed forums, Facebook page, and open/closed issues on Github to find a solution to this issue. Found two other recent instances of this problem with one referenced here (https://github.com/FalconChristmas/fpp/issues/1633).

Came across this problem (https://github.com/FalconChristmas/fpp/issues/227) from 2016 where the USB storage option wasn't un-commented in /etc/fstab. Checked my system and sure enough the line for the SD card (/dev/mmcblk0p1) was commented out. Edited the fstab file in the shell to remove the comments and re-booted the system and SD card showed as mounted and was able to change the storage location successfully.

Looking through the code files, I believe the line to mount the SD card is being commented out during the script that is ran (BBB-FlashMMC.sh) when flashing FPP to the eMMC, but not 100% sure on that yet.

**Additional Attachments**
No logs created.

**Comment by darylc** [comment] 2024-02-17 05:08
duplicate of #1633

**Closed by darylc** 2024-02-17 05:08 UTC
