### ISSUE TITLE
Audio artifacts when using a combination of VLC and VAST to stream internet audio

### ISSUE THREAD

**Issue by nmiller0113** [FalconChristmas/fpp#1393] opened 2022-10-26 19:04 UTC
I've attached the logs, but I'm not sure they'll be of any value as I've reviewed them and have not seen anything related or of value:
[FPP_Logs_20221026.1841.zip](https://github.com/FalconChristmas/fpp/files/9872829/FPP_Logs_20221026.1841.zip)

# Please answer the following:
**FPP Version and Hardware**:  I've tested this on FPP 6.1.1 on both the BBB and RPI. Both exhibit the same behavior. Both brand new fresh 6.1 installations...NOT UPGRADES.

**Plugin and additional hardware**: Vast plugin (latest version) and VAST FM Transmitter. I can provide my vast configuration if needed, but I don't believe this is related. I used the same hardware and configuration on the latest version of 5.5 for the last six months without a single issue...also non-streaming local audio for my sequences works great in 6.1.1; it's only the streaming audio. I run the audio streaming service as well, and the quality is also not an issue...you can test it yourself at http://stream.themillerhome.org:8000/lights

**Describe the bug and Steps to reproduce**: 
I call the MP3StreamerStart.sh script at the end of my show playlist so that it streams my internet radio station between shows and overnight. While it's streaming, I can hear a clicking or clipping consistently and pretty clearly. I do not have any audio issues with playing local audio files, so I assume it's something to do with VLC. This did not happen with the latest version of 5.5, which I ran on the same hardware for six months without issue. I can reproduce this on both the RPI and BBB.

**Expected behavior**: 
There is no clicking or clipping for streaming audio

**Additional context**: 
I did experience a strange issue where on the BBB when I called for the script to stop in the playlist, it wouldn't...it would just fade and then continue. I had to switch to an FPP Command to run the stop script to correct that. I don't experience that same behavior on the RPI. While this isn't related to the audio issues, I thought it was still something of value to note.

**Comment by nmiller0113** [comment] 2022-10-26 23:25
I reviewed the VLC version we have, which appears to be a nightly compiled build (revision 4.0.0-dev-20176-ge9a882d3e1) from July. I looked through the VLC bug tracker but couldn't find any correlations. I could only see that there have been quite a few builds since then...so fingers crossed that someone else already reported this and it was fixed in a later build :)

**Comment by nmiller0113** [comment] 2022-11-09 22:08
I've revised the title of this case as I recently uncovered more while testing a fresh install of 6.2. I didn't expect it to be fixed in that version because nothing in the changelog mentioned audio-related changes.

I know that @dkulp uses Vast, so hopefully, he sees this as it is easily reproducible on versions 6.2....and 6.1.1. here are the exact steps to reproduce the clipping/clicking audio every time:

1. Have Vast FM Transmitter plugin and USB device installed and selected as the Audio Output Device in FPP
2. Use VLC to play the internet audio stream, either via CLI "sudo cvlc -q --no-video-title-show http://stream.themillerhome.org:8000/lights" or through the WebUI calling the MP3StreamerStart.sh script.

That's it. You should get the same sound artifacts I'm hearing. I mentioned previously that [mpd/Music Player Daemon](https://www.musicpd.org/), installed with the After Hours Music plugin, does not experience this issue in the same configuration mentioned above...this is why I mentioned VLC as being suspect.

**_In my installation and tests with 6.2 today_** I discovered that I also don't get sound artifacts when using the local RPI4 bcm2835 ALSA (Pi Onboard Audio). So this means it's an issue when using a combination of both Vast and VLC, since each can work independently of each other:

- Vast works with the Music Player Daemon/After Hours Plugin (it also works for FPP sequence audio)
- VLC works fine when using the local RPI4 bcm2835 ALSA (Pi Onboard Audio)

_BUT_ VLC and Vast together produce audio clipping/clicking artifacts

I hope this helps the developers narrow down the issue. I'd love to get this working properly as it did until the latest version of FPP 5.x. Thank you!

**Comment by patdelaney** [comment] 2022-11-15 21:57
I am able to reproduce it as well but you need a USB audio device. For my test I was using the Behringer Xenyx USB Mixer and I could hear the artifacts. If I switched to onboard 3.5 mini audio output the audio was fine. I will test with Soundblaster 3 dongle as well.  This was on a Piv3.

**Comment by patdelaney** [comment] 2022-11-15 22:04
I can reproduce it with usb soundblaster as well

**Comment by nmiller0113** [comment] 2022-11-15 22:33
Thanks for confirming it @patdelaney! Hopefully, the fix isn't too tricky, as I used it heavily last year in between shows.

**Comment by patdelaney** [comment] 2022-11-19 17:16
I found a workaround that seems to work for now until a more permanent fix is in place:

Open ssh session to the fpp

run aplay -l

Identify the USB Device: (my example on PiV3)

fpp@FPPv3-6:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 3/3
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
**card 2: S3 [Sound Blaster Play! 3], device 0: USB Audio [USB Audio]**
  Subdevices: 1/1
  Subdevice #0: subdevice #0

I then edited the STREAMOPTIONS variable and added --alsa-audio-device hw:2,0 to the beginning of the line.
-where the 2 in the hw:2,0  line is the Card 2 above

So now it looks like this:
STREAMOPTIONS="--alsa-audio-device hw:2,0 -q --no-video-title-show"

Save the file and run it

I'm just not sure how to fix this in code or why manually selecting the device in the oprions fixes it.

**Comment by nmiller0113** [comment] 2023-01-04 21:23
@patdelaney - when working on another issue (https://github.com/FalconChristmas/fpp/issues/1427) I learned that the audio artifacts/clipping only happens when running the MP3StreamerStart.sh script from within FPP. I mentioned it here https://github.com/FalconChristmas/fpp/issues/1427#issuecomment-1371431203 specifically, but if I execute the script from the command line ssh'd into FPP `cvlc -q --no-video-title-show http://stream.themillerhome.org:8000/lights & echo $! >/var/run/mp3streamer.pid` I don't get any clipping or audio artifacts...the audio sounds perfect.

I know there was a buffer change pushed by @dkulp to potentially correct this https://github.com/FalconChristmas/fpp/commit/14b8ff7f593b0c2ee9bfca4e9e35a79bb9312de7, but I'm still running 6.2 and haven't updated anything. I'm sharing this since it seems it may not be a buffer issue since it doesn't happen when triggered from within the CLI. Thoughts?

**Comment by darylc** [comment] 2023-01-04 22:55
@nmiller0113 Please test the commit you reference 14b8ff7 and let us know if it fixes it.

**Comment by nmiller0113** [comment] 2023-01-04 23:41
@darylc, I'm more than happy to, but can you help me to understand why this is needed? I'd like to better understand since running the command from the CLI doesn't have the issue that it does when executed from within FPP. It doesn't make sense to me why the buffer setting would be needed for one but not the other when they are calling the same script...just in different ways.

I'm also trying to learn why the difference between the two ways to execute requires a buffer setting change.

**Comment by pdelaney-cuna** [comment] 2023-01-05 12:43
I see @nmiller0113 point. While the buffers change does correct the initial reported problem. I feel that fact that it doesn't happen when FPP doesn't initial the script is worth looking into. The buffer fix may just be a hiding what the real issue is.

**Comment by pdelaney-cuna** [comment] 2023-01-05 12:54
I tested the fix and it works, but based on his comments, is the buffer change hiding a different problem.

**Comment by nmiller0113** [comment] 2023-01-05 20:30
Thanks @pdelaney-cuna / @patdelaney (not sure which I should be mentioning now haha)! That was the point I was trying to clarify. The buffer change appears to be masking the real problem, not correcting it. The buffer change may not even be required and could possibly even be reverted, as I recall you mentioning there was concern that changing it could cause audio delays.

@darylc, I know that @dkulp could likely test it since I got the idea for my current setup based on his hardware configuration. I'm sure Dan is busy, and this isn't a high priority at the moment as it's the off-season, but I'm hoping it can be figured out before next season.

Thanks again!

**Closed** 2023-05-13 06:37 UTC

**Comment by nmiller0113** [comment] 2023-06-13 23:59
@darylc @dkulp I realized this was closed when we've not determined the root cause. Or did we determine it, and I just missed it? As noted above, the buffer fix originally pushed was not the root cause.

> I see @nmiller0113 point. While the buffers change does correct the initially reported problem. I feel that fact that it doesn't happen when FPP doesn't initial the script is worth looking into. The buffer fix may just be hiding what the real issue is.

**Comment by nmiller0113** [comment] 2023-09-16 22:28
@darylc @dkulp, I'm just checking if you saw my message above. I'm still curious as to the root cause.

**Comment by dkulp** [comment] 2023-09-17 18:07
Not something I care to spend any time tracking down.   The fix works.

**Comment by nmiller0113** [comment] 2023-09-17 21:00
Sounds good @dkulp, I was only asking as I believe there was a concern with the change potentially causing sync/delay issues with the music.
