### ISSUE TITLE
Background effects are not overridden when a sequence is playing.

### ISSUE THREAD

**Issue by cpinkham** [FalconChristmas/fpp#975] opened 2021-02-24 05:12 UTC
In the latest FPP v4.x and master, playing a sequence in the foreground while an effect is running in background mode does not work.

Steps to reproduce:
- start a background effect
- start a sequence

Expected:
- sequence plays and background effect is paused

What is seen:
- sequence appears to be playing as reported in the UI, but the lights do not light up with sequence data.  The effect continues to play instead.

**Comment by darylc** [comment] 2021-05-31 11:15
I setup a test for this on master, and I can't replicate it.  Running a sequence works on the 2 props, then starting/stopping an effect sequence in the background to control just one of those props worked ok.

**Comment by darylc** [comment] 2021-06-06 10:34
Found the original thread about this - https://falconchristmas.com/forum/index.php/topic,14102.msg117987.html

The issue is with FSEQ running as an effect, not effects (ESEQ)

**Comment by dkulp** [comment] 2023-04-10 19:01
I'm not seeing any behavioral differences between eseq and fseq files.    They both behave exactly the same.  

That said, the default for "Pause background effects during FSEQ playback" is "Off" so by default, background effects are NOT paused.   That default value likely should be changed.

**Comment by darylc** [comment] 2023-06-16 23:51
Closing for now.  If someone can replicate this problem in fpp v6 or 7, it can be reopened.

**Closed by darylc** 2023-06-16 23:51 UTC
