### ISSUE TITLE
FPPD/RPI Crash mid-playlist w/USB Audio Out

### ISSUE THREAD

**Issue by letsrollusafa11** [FalconChristmas/fpp#908] opened 2020-12-06 15:36 UTC
[FPP_Logs_20201206.1532.zip](https://github.com/FalconChristmas/fpp/files/5649031/FPP_Logs_20201206.1532.zip)
**Describe the bug and Steps to reproduce**: 

When manually starting a playlist (or by scheduling) songs will make it a random amount of time through a playlist before stalling and rebooting the device. I've narrowed down the issue to only happening when I have a USB Audio Out Device connected (tried two different USB devices, Logitech USB Audio Out and SoundBlaster3 Audio Out). I've removed my FM transmitter from the possible problems as the issue continues to happen when the FM transmitter is turned off. 

After the playlist goes to "Idle" after the crash:

>Status/Control > FPP Settings > Audio/Video > Audio Output Device
The USB device that is currently connected disappears from this list and defaults to the bcm2835 Pi-Onboard Audio. 

From fppd.log>
```
2020-12-05 20:29:34.870 (2724) mediaoutput/SDLOut.cpp:264: Stalled audio, buffers still filling.                                                                                                                   
2020-12-05 20:29:34.870 (2724) mediaoutput/SDLOut.cpp:264: Stalled audio, buffers still filling.                                                                                                                   
2020-12-05 20:29:35.382 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:36.312 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:37.202 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:38.133 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:39.013 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:39.932 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:40.833 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:41.763 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:42.653 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:43.579 (2679) mediaoutput/SDLOut.cpp:1012: Audio has stalled   0                                                                                                                                  
2020-12-05 20:29:46.513 (2679) fppd.c:683: Shutting down main loop.                                                                                                                                                
2020-12-05 20:29:47.513 (2679) Scheduler.cpp:839: Current Schedule: (Status: '+' = Enabled, '-' = Disabled, '!' = Outside Date Range, '*' = Repeat, Stop (G)raceful/(L)oop/(H)ard                                  
2020-12-05 20:29:47.514 (2679) Scheduler.cpp:840: Stat Start & End Dates       Days         Start & End Times   Playlist                                                                                           
2020-12-05 20:29:47.514 (2679) Scheduler.cpp:841: ---- ----------------------- ------------ ------------------- ---------------------------------------------                                                      
2020-12-05 20:29:47.514 (2679) fppd.c:869: Stopping channel output thread.                                                                                                                                         
2020-12-05 20:29:47.945 (2679) fppd.c:225: Crash handler called:  7                                                                                                                                                
2020-12-05 20:29:59.072 (1236) log.c:232: =========================================                                                                                                                                
2020-12-05 20:29:59.076 (1236) log.c:233: FPP 4.5.1-5-g1f787185                                                                                                                                                    
2020-12-05 20:29:59.076 (1236) log.c:234: Branch: v4.5                                                                                                                                                             
2020-12-05 20:29:59.076 (1236) log.c:235: =========================================                                                                                                                                
2020-12-05 20:29:59.083 (1236) common.cpp:665: JSON File /home/fpp/media/config/schedule.json does not exist                                                                                                       
2020-12-05 20:29:59.142 (1236) channeloutput/channeloutput.c:359: UDPOutput 0:  Determined range needed 0 - 8160      
[FPP_Logs_20201206.1532.zip](https://github.com/FalconChristmas/fpp/files/5649023/FPP_Logs_20201206.1532.zip)
```

Further Info:
I've also replicated issue on a PI4 board as well.

Version Info | 
FPP Version: | v4.5.1-5-g1f787185
Platform: | Raspberry Pi (Pi 3 Model B+)
FPP OS Build: | v4.4
OS Version: | Raspbian GNU/Linux 10 (buster)
Hardware Serial Number: | 00000000827fa467
Kernel Version: | 5.4.72-v7+
Local Git Version: | 1f78718 
Remote Git Version: | 1f78718

**Comment by bigwavedave42** [comment] 2020-12-06 18:32
I'd recommend trying to move your USB Audio to be connected to a powered USB hub, which is then connected to the Pi.  It might be that there is a power dip when the Pi is under load (playing a sequence) and it is causing the USB Audio to starve for power and get flaky.  I've seen this before and using a powered USB hub solved it.  If that solves it, you could investigate other things to determine where the problem is... but it is an easy thing to test.

**Comment by darylc** [comment] 2021-06-20 01:55
@letsrollusafa11 Have you tried the things that bigwavedave42 suggested to see if this solves it yet?

**Comment by darylc** [comment] 2021-07-25 08:33
@ghormann Lets close this for now

**Comment by ghormann** [comment] 2021-07-25 14:24
Closed do to lack of reply.

**Closed by ghormann** 2021-07-25 14:24 UTC
Labels: Need Info

**Comment by SarahDods** [comment] 2022-12-10 02:01
I'm having an identical problem running through USB audio.  Was there ever a fix found?

**Comment by SarahDods** [comment] 2022-12-10 03:26
Confirmed connecting the pi audio output to a powered USB hub and then to sound card fixes the problem.  Thanks for the guidance.  After 6 nights of debugging, I was running out of ideas.
