### ISSUE TITLE
Notification needed when unable to write files

### ISSUE THREAD

**Issue by forkineye** [FalconChristmas/fpp#160] opened 2015-10-08 14:42 UTC
I had a USB drive on my Pi B+ end up with the FAT32 dirty bit set, causing it to mount read-only.  It occurred during a power-cycle or reboot as it never left the Pi.  I figured this out after multiple uploads of my sequences and wondering why they weren't updating.  From the web interface, they were uploading and everything seemed fine.  An error notification when uploading / saving of data would be nice.  Or maybe just check filesystem state at boot and notify the user on the home page / provide them instructions to fix it (ssh in, kill fpp, kill apache, umount the drive, fsck it, etc...).

**Comment by darylc** [comment] 2021-06-20 04:48
read only media file systems were largely caused by fsck seg faulting on it's check during bootup which was fixed in more recent versions.  I propose we close this issue.

**Closed** 2021-06-20 14:26 UTC
