### ISSUE TITLE
Playlist edit works with only rename ,not delete

### ISSUE THREAD

**Issue by Kamal-Sonani** [FalconChristmas/fpp#627] opened 2019-12-19 03:31 UTC
I created 2 playlist by mistake by pressing create playlist button.

I'm only able to rename it instead of delete.

**Comment by cpinkham** [comment] 2019-12-25 21:25
Which button are you referring to?  The button to create a playlist is called 'Add' on the Playlist Editor screen in FPP and it doesn't allow creating two playlists with the same name.  I am unable to reproduce the delete issue you are referring to as well.

**Comment by Kamal-Sonani** [comment] 2019-12-28 06:09
Try to delete any playlist.

**Comment by cpinkham** [comment] 2020-01-16 05:10
Again, I am on a FPP SD image running the latest code and am unable to reproduce this issue.  I can not create two playlists by the same name and I can successfully delete playlists.  This sounds like it may be a storage or other issue.  Check the apache error log in the Logs tab of the FPP File Manager and see if there is any info in there.  Closing this ticket until it can be determined that this is an actual issue.

**Closed by cpinkham** 2020-01-16 05:10 UTC
